
#pragma once
#include "TreeGrowthData.hpp"

using namespace evo_engine;
namespace eco_sys_lab_plugin {
/**
 * \brief Controls the growth parameters of a tree shoot.
 */
struct ShootGrowthController {
  /**
   * \brief Determines whether branches should push growth.
   */
  bool branch_push = false;

  /**
   * \brief Indicates whether to use level-based apical control.
   */
  bool use_level_for_apical_control = false;

#pragma region Internode
  /**
   * \brief The base count of internodes.
   */
  int base_internode_count = 1;

  /**
   * \brief The mean and variance of the angular difference between the growth direction and the direction of the apical
   * bud.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)>
      base_node_apical_angle;

  /**
   * \brief The expected elongation length for an internode for one year.
   */
  float internode_growth_rate;

  /**
   * \brief The mean and variance of the angle between the direction of a lateral bud and its parent shoot.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> branching_angle;

  /**
   * \brief The mean and variance of an angular difference orientation of lateral buds between two internodes.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> roll_angle;

  /**
   * \brief The mean and variance of the angular difference between the growth direction and the direction of the apical
   * bud.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> apical_angle;

  /**
   * \brief The gravitropism factor affecting internode growth.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> gravitropism;

  /**
   * \brief The phototropism factor affecting internode growth.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> phototropism;

  /**
   * \brief The horizontal tropism affecting internode orientation.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)>
      horizontal_tropism;

  /**
   * \brief The strength of gravity bending for the internode.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> sagging;

  /**
   * \brief The internode length.
   */
  float internode_length;

  /**
   * \brief Factor by which thickness affects internode length.
   */
  float internode_length_thickness_factor = 0.0f;

  /**
   * \brief Thickness of the end internode.
   */
  float end_node_thickness;

  /**
   * \brief The thickness accumulation factor for internodes.
   */
  float thickness_accumulation_factor;

  /**
   * \brief Extra thickness gained from internode length with age.
   */
  float thickness_age_factor;

  /**
   * \brief The shadow volume factor affecting internode growth.
   */
  float internode_shadow_factor = 1.f;
#pragma endregion

#pragma region Bud
  /**
   * \brief The number of lateral buds an internode contains.
   */
  std::function<int(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> lateral_bud_count;

  /**
   * \brief Extinction rate of the apical bud.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)>
      apical_bud_extinction_rate;

  /**
   * \brief Flushing rate of a lateral bud.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)>
      lateral_bud_flushing_rate;

  /**
   * \brief Controls the apical dominance effect.
   */
  float apical_control;

  /**
   * \brief Root distance control affecting bud growth.
   */
  float root_distance_control;

  /**
   * \brief Height control factor affecting bud growth.
   */
  float height_control;

  /**
   * \brief Determines the inhibitor amount generated by an internode.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)>
      apical_dominance;

  /**
   * \brief The amount of inhibitor lost when passing through a branch.
   */
  float apical_dominance_loss;

  /**
   * \brief Strength of the internode which affects bud growth.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)>
      internode_strength;
#pragma endregion

#pragma region Pruning
  /**
   * \brief The breaking force required to prune an internode.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> breaking_force;

  /**
   * \brief Impact of incoming light on the shedding of end internodes from end to root.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, ClimateModel& climate_model,
                      const ShootSkeleton& shoot_skeleton, const SkeletonNode<InternodeGrowthData>& internode)>
      end_to_root_pruning_factor;

  /**
   * \brief Impact of incoming light on the shedding of end internodes from root to end.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, ClimateModel& climate_model,
                      const ShootSkeleton& shoot_skeleton, const SkeletonNode<InternodeGrowthData>& internode)>
      root_to_end_pruning_factor;
#pragma endregion

#pragma region Leaf
  /**
   * \brief Controls leaf growth in internodes.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> leaf;

  /**
   * \brief The probability of a leaf falling when health reaches zero.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)>
      leaf_fall_probability;
#pragma endregion

#pragma region Fruit
  /**
   * \brief Controls fruit growth in internodes.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)> fruit;

  /**
   * \brief The probability of a fruit falling when health reaches zero.
   */
  std::function<float(std::mt19937& random_engine, const SkeletonNode<InternodeGrowthData>& internode)>
      fruit_fall_probability;
#pragma endregion
};
}  // namespace eco_sys_lab_plugin
