
#pragma once
#include "ClimateModel.hpp"
#include "RootGrowthData.hpp"
#include "ShootGrowthData.hpp"
using namespace evo_engine;
namespace eco_sys_lab_plugin {
/**
 * \brief Controls the growth parameters of a tree shoot.
 */
struct ShootGrowthController {
  /**
   * \brief Determines whether branches should push growth.
   */
  bool branch_push = true;

#pragma region Internode
  /**
   * \brief The base count of internodes.
   */
  int root_internode_count = 1;

  /**
   * \brief The expected elongation length for an internode for one year.
   */
  float internode_growth_rate;

  /**
   * \brief The mean and variance of the angle between the direction of a lateral bud and its parent shoot.
   */
  std::function<glm::quat(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                          const SkeletonNode<InternodeGrowthData>& internode, const Bud& bud)>
      bud_rotation;
  /**
   * \brief The tropism factor affecting internode growth direction.
   */
  std::function<void(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                     const SkeletonNode<InternodeGrowthData>& internode, glm::quat& rotation)>
      tropism;

  /**
   * \brief The strength of gravity bending for the internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      sagging;

  /**
   * \brief The base internode length.
   */
  float base_internode_length;

  /**
   * \brief Current internode length.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      internode_length;

  /**
   * \brief The base thickness of the internode.
   */
  float base_thickness;

  /**
   * \brief Current thickness.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      thickness;

  /**
   * \brief The thickness accumulation factor for internodes.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      thickness_accumulation_factor;

  /**
   * \brief The shadow volume factor affecting internode growth.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      shadow_size;
#pragma endregion

  /**
   * \brief The number of lateral buds an internode contains.
   */
  std::function<int(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                    const SkeletonNode<InternodeGrowthData>& internode)>
      lateral_bud_count;

  /**
   * \brief Extinction rate of the bud.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      bud_flushing_rate;

  /**
   * \brief Extinction rate of the bud.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_potential;

  /**
   * \brief Determines the inhibitor amount generated by an internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_inhibitor;

  /**
   * \brief The amount of inhibitor lost when passing through a branch.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_inhibitor_transport_reduction;
};

/**
 * \brief Controls the growth parameters of a tree shoot.
 */
struct RootGrowthController {};

struct FoliageController {
  /**
   * \brief Calculate how many leaves for current node.
   */
  std::function<uint32_t(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                         const SkeletonNode<InternodeGrowthData>& internode)>
      leaf_count;
  /**
   * \brief Controls leaf formulation in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, Leaf& leaf,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      leaf_formulation;

  /**
   * \brief Controls leaf growth in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, float delta_time, Leaf& leaf,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      leaf_growth;
};

struct ReproductionController {
  /**
   * \brief Calculate how many modules for current node.
   */
  std::function<uint32_t(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                         const SkeletonNode<InternodeGrowthData>& internode)>
      module_count;
  /**
   * \brief Controls flower formulation in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, Flower& leaf,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      flower_formulation;
  /**
   * \brief Controls flower growth in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, float delta_time, Flower& flower,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      flower_growth;
  /**
   * \brief Controls fruit formulation in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, Fruit& fruit,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      fruit_formulation;
  /**
   * \brief Controls fruit growth in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, float delta_time, Fruit& fruit,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      fruit_growth;
};

/**
 * \brief Controls the pruning parameters of a tree shoot.
 */
struct ShootPruningController {
#pragma region Pruning
  /**
   * \brief Strength of the internode which affects bud growth.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      internode_strength;
  /**
   * \brief The breaking force required to prune an internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      breaking_force;

  /**
   * \brief Impact of incoming light on the shedding of end internodes from end to root.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, ClimateModel& climate_model,
                      const ShootSkeleton& shoot_skeleton, const SkeletonNode<InternodeGrowthData>& internode)>
      end_to_root_pruning_factor;

  /**
   * \brief Impact of incoming light on the shedding of end internodes from root to end.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, ClimateModel& climate_model,
                      const ShootSkeleton& shoot_skeleton, const SkeletonNode<InternodeGrowthData>& internode)>
      root_to_end_pruning_factor;
#pragma endregion
};
}  // namespace eco_sys_lab_plugin
