
#pragma once
#include "ClimateModel.hpp"
#include "TreeGrowthData.hpp"
using namespace evo_engine;
namespace eco_sys_lab_plugin {
/**
 * \brief Controls the growth parameters of a tree shoot.
 */
struct ShootGrowthController {
  /**
   * \brief Determines whether branches should push growth.
   */
  bool branch_push = false;

  /**
   * \brief Indicates whether to use level-based apical control.
   */
  bool use_level_for_apical_control = false;

#pragma region Internode
  /**
   * \brief The base count of internodes.
   */
  int root_internode_count = 1;

  /**
   * \brief The expected elongation length for an internode for one year.
   */
  float internode_growth_rate;

  /**
   * \brief The mean and variance of the angle between the direction of a lateral bud and its parent shoot.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      branching_angle;

  /**
   * \brief The mean and variance of an angular difference orientation of lateral buds between two internodes.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      roll_angle;

  /**
   * \brief The mean and variance of the angular difference between the growth direction and the direction of the apical
   * bud.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      apical_angle;

  /**
   * \brief The gravitropism factor affecting internode growth.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      gravitropism;

  /**
   * \brief The phototropism factor affecting internode growth.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      phototropism;

  /**
   * \brief The horizontal tropism affecting internode orientation.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      horizontal_tropism;

  /**
   * \brief The strength of gravity bending for the internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      sagging;

  /**
   * \brief The base internode length.
   */
  float base_internode_length;

  /**
   * \brief Current internode length.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      internode_length;

  /**
   * \brief The base thickness of the internode.
   */
  float base_thickness;

  /**
   * \brief Current thickness.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      thickness;

  /**
   * \brief The thickness accumulation factor for internodes.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      thickness_accumulation_factor;

  /**
   * \brief The shadow volume factor affecting internode growth.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      shadow_size;
#pragma endregion

#pragma region Bud
  /**
   * \brief The number of lateral buds an internode contains.
   */
  std::function<int(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                    const SkeletonNode<InternodeGrowthData>& internode)>
      lateral_bud_count;

  /**
   * \brief Extinction rate of the bud.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      bud_flushing_rate;

  /**
   * \brief Extinction rate of the bud.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_potential;

  /**
   * \brief Determines the inhibitor amount generated by an internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_inhibitor;

  /**
   * \brief The amount of inhibitor lost when passing through a branch.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_inhibitor_transport_reduction;

#pragma endregion

#pragma region Leaf
  /**
   * \brief Controls leaf growth in internodes.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      leaf;

  /**
   * \brief The probability of a leaf falling when health reaches zero.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      leaf_fall_probability;
#pragma endregion

#pragma region Fruit
  /**
   * \brief Controls fruit growth in internodes.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      fruit;

  /**
   * \brief The probability of a fruit falling when health reaches zero.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      fruit_fall_probability;
#pragma endregion
};

/**
 * @struct TreePruningSettings
 * @brief Defines settings for pruning operations on the tree.
 */
struct TreePruningSettings {
  float low_branch_pruning = 0.f;  ///< Factor defining low branch pruning.

  /**
   * @brief Inspects pruning settings in an editor.
   * @param editor_layer The editor layer managing inspection.
   * @return True if data was not modified during inspection.
   */
  bool OnInspect(const std::shared_ptr<EditorLayer>& editor_layer);

  /**
   * @brief Saves pruning settings to a YAML emitter.
   * @param name The name of the settings entry.
   * @param out The YAML emitter to serialize data into.
   */
  void Save(const std::string& name, YAML::Emitter& out) const;

  /**
   * @brief Loads pruning settings from a YAML node.
   * @param name The name of the settings entry.
   * @param in The YAML node containing serialized data.
   */
  void Load(const std::string& name, const YAML::Node& in);
};

/**
 * \brief Controls the pruning parameters of a tree shoot.
 */
struct ShootPruningController {
#pragma region Pruning
  /**
   * \brief Strength of the internode which affects bud growth.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      internode_strength;
  /**
   * \brief The breaking force required to prune an internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      breaking_force;

  /**
   * \brief Impact of incoming light on the shedding of end internodes from end to root.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, ClimateModel& climate_model,
                      const ShootSkeleton& shoot_skeleton, const SkeletonNode<InternodeGrowthData>& internode)>
      end_to_root_pruning_factor;

  /**
   * \brief Impact of incoming light on the shedding of end internodes from root to end.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, ClimateModel& climate_model,
                      const ShootSkeleton& shoot_skeleton, const SkeletonNode<InternodeGrowthData>& internode)>
      root_to_end_pruning_factor;
#pragma endregion
};
}  // namespace eco_sys_lab_plugin
