
#pragma once
#include "ClimateModel.hpp"
#include "RootGrowthData.hpp"
#include "ShootGrowthData.hpp"
#include "VoxelSoilModel.hpp"
using namespace evo_engine;
namespace eco_sys_lab_plugin {
struct ITreeController {
  [[nodiscard]] bool Initialized() const;

 private:
  friend class Tree;
  bool initialized_ = false;
};

/**
 * \brief Controls the growth parameters of a tree shoot.
 */
struct ShootGrowthController : ITreeController {
  /**
   * \brief Determines whether branches should push growth.
   */
  bool branch_push = true;

#pragma region Internode
  /**
   * \brief The base count of internodes.
   */
  int base_internode_count = 1;

  /**
   * \brief The expected elongation length for an internode for one year.
   */
  float internode_growth_rate;
  std::function<void(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                     SkeletonNode<InternodeGrowthData>& shoot_node)>
      base_node_initialization;
  /**
   * \brief The initial rotation of the angle between the direction of a bud and its parent shoot.
   */
  std::function<glm::quat(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                          const SkeletonNode<InternodeGrowthData>& internode, const Bud& bud)>
      bud_rotation;
  /**
   * \brief The tropism factor affecting internode growth direction.
   */
  std::function<void(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                     const SkeletonNode<InternodeGrowthData>& old_internode,
                     const SkeletonNode<InternodeGrowthData>& new_internode, glm::quat& rotation)>
      tropism;

  /**
   * \brief The strength of gravity bending for the internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      sagging;

  /**
   * \brief The base internode length.
   */
  float base_internode_length;

  /**
   * \brief Current internode length.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      internode_length;

  /**
   * \brief The base thickness of the internode.
   */
  float base_thickness;

  /**
   * \brief Current thickness.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      thickness;

  /**
   * \brief The thickness accumulation factor for internodes.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      thickness_accumulation_factor;

  /**
   * \brief The shadow volume factor affecting internode growth.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      shadow_size;
#pragma endregion

  /**
   * \brief The number of lateral buds an internode contains.
   */
  std::function<int(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                    const SkeletonNode<InternodeGrowthData>& internode)>
      lateral_bud_count;

  /**
   * \brief Extinction rate of the bud.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      bud_flushing_rate;

  /**
   * \brief Extinction rate of the bud.
   */
  std::function<float(std::mt19937& random_engine, const ShootSkeleton& shoot_skeleton,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_potential;

  /**
   * \brief Determines the inhibitor amount generated by an internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_inhibitor;

  /**
   * \brief The amount of inhibitor lost when passing through a branch.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data, float growth_inhibitor,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      growth_inhibitor_transport;
};

struct FoliageController : ITreeController {
  /**
   * \brief Calculate how many leaves for current node.
   */
  std::function<uint32_t(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                         const SkeletonNode<InternodeGrowthData>& internode)>
      leaf_count;
  /**
   * \brief Controls leaf formulation in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, Leaf& leaf,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      leaf_formulation;

  /**
   * \brief Controls leaf growth in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, float delta_time, Leaf& leaf,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      leaf_growth;
};

struct ShootReproductionController : ITreeController {
  /**
   * \brief Calculate how many modules for current node.
   */
  std::function<uint32_t(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                         const SkeletonNode<InternodeGrowthData>& internode)>
      module_count;
  /**
   * \brief Controls flower formulation in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, Flower& leaf,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      flower_formulation;
  /**
   * \brief Controls flower growth in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, float delta_time, Flower& flower,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      flower_growth;
  /**
   * \brief Controls fruit formulation in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, Fruit& fruit,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      fruit_formulation;
  /**
   * \brief Controls fruit growth in internodes.
   */
  std::function<bool(std::mt19937& random_engine, const glm::mat4& global_transform, float delta_time, Fruit& fruit,
                     const ClimateModel& climate_model, const ShootSkeleton& shoot_skeleton,
                     const SkeletonNode<InternodeGrowthData>& internode)>
      fruit_growth;
};

/**
 * \brief Controls the pruning parameters of a tree shoot.
 */
struct ShootPruningController : ITreeController {
#pragma region Pruning
  /**
   * \brief Strength of the internode which affects bud growth.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      internode_strength;
  /**
   * \brief The breaking force required to prune an internode.
   */
  std::function<float(std::mt19937& random_engine, const ShootGrowthData& shoot_growth_data,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      breaking_force;

  /**
   * \brief Impact of incoming light on the shedding of end internodes from end to root.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, const ClimateModel& climate_model,
                      const VoxelSoilModel& soil_model, const ShootSkeleton& shoot_skeleton,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      end_to_base_pruning_factor;

  /**
   * \brief Impact of incoming light on the shedding of end internodes from root to end.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, const ClimateModel& climate_model,
                      const VoxelSoilModel& soil_model, const ShootSkeleton& shoot_skeleton,
                      const SkeletonNode<InternodeGrowthData>& internode)>
      base_to_end_pruning_factor;
#pragma endregion
};

/**
 * \brief Controls the growth parameters of a tree root.
 */
struct RootGrowthController : ITreeController {
  /**
   * \brief The expected elongation length for an internode for one year.
   */
  float root_node_growth_rate;
  /**
   * \brief The base count of root nodes.
   */
  int base_root_node_count = 1;
  /**
   * \brief The base thickness of the root node.
   */
  float base_thickness;
  /**
   * \brief The base length of root nodes.
   */
  float base_root_node_length;

  std::function<void(std::mt19937& random_engine, const RootGrowthData& root_growth_data,
                     SkeletonNode<RootNodeGrowthData>& root_node)>
      base_node_initialization;

  /**
   * \brief Current thickness.
   */
  std::function<float(std::mt19937& random_engine, const RootGrowthData& root_growth_data,
                      const SkeletonNode<RootNodeGrowthData>& root_node)>
      thickness;

  /**
   * \brief The thickness accumulation factor for root nodes.
   */
  std::function<float(std::mt19937& random_engine, const RootGrowthData& root_growth_data,
                      const SkeletonNode<RootNodeGrowthData>& root_node)>
      thickness_accumulation_factor;

  /**
   * \brief Current root node length.
   */
  std::function<float(std::mt19937& random_engine, const RootGrowthData& root_growth_data,
                      const SkeletonNode<RootNodeGrowthData>& root_node)>
      root_node_length;

  /**
   * \brief Extinction rate of the bud.
   */
  std::function<float(std::mt19937& random_engine, const RootSkeleton& root_skeleton,
                      const SkeletonNode<RootNodeGrowthData>& root_node)>
      growth_potential;

  /**
   * \brief Determines the inhibitor amount generated by an root node.
   */
  std::function<float(std::mt19937& random_engine, const RootGrowthData& root_growth_data,
                      const SkeletonNode<RootNodeGrowthData>& root_node)>
      growth_inhibitor;

  /**
   * \brief The amount of inhibitor lost when passing through a branch.
   */
  std::function<float(std::mt19937& random_engine, const RootGrowthData& shoot_growth_data,
                      const float growth_inhibitor, const SkeletonNode<RootNodeGrowthData>& internode)>
      growth_inhibitor_transport;

  /**
   * \brief The tropism factor affecting root node growth direction.
   */
  std::function<void(std::mt19937& random_engine, const RootGrowthData& root_growth_data,
                     const SkeletonNode<RootNodeGrowthData>& old_node, SkeletonNode<RootNodeGrowthData>& new_node,
                     glm::quat& rotation)>
      tropism;
  /**
   * \brief The mean and variance of the angle between the direction of a node and its parent shoot.
   */
  std::function<glm::quat(std::mt19937& random_engine, const RootGrowthData& root_growth_data,
                          const SkeletonNode<RootNodeGrowthData>& old_node,
                          const SkeletonNode<RootNodeGrowthData>& new_node)>
      node_rotation;

  /**
   * \brief Flushing rate of the lateral node.
   */
  std::function<float(std::mt19937& random_engine, const RootGrowthData& root_growth_data,
                      const SkeletonNode<RootNodeGrowthData>& root_node)>
      lateral_node_flushing_rate;
};

struct FineRootController : ITreeController {};

struct RootReproductionController : ITreeController {};

struct RootPruningController : ITreeController {
  /**
   * \brief Impact of incoming light on the shedding of end node from end to base.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, const ClimateModel& climate_model,
                      const VoxelSoilModel& soil_model, const RootSkeleton& shoot_skeleton,
                      const SkeletonNode<RootNodeGrowthData>& node)>
      end_to_base_pruning_factor;

  /**
   * \brief Impact of incoming light on the shedding of end node from base to end.
   */
  std::function<float(std::mt19937& random_engine, const glm::mat4& global_transform, const ClimateModel& climate_model,
                      const VoxelSoilModel& soil_model, const RootSkeleton& shoot_skeleton,
                      const SkeletonNode<RootNodeGrowthData>& node)>
      base_to_end_pruning_factor;
};

}  // namespace eco_sys_lab_plugin
