#pragma once

// ---------------------------------------------------------------------------
// OrganMeshPly
//
// Phase 1 QA helper. Writes an explicit triangle mesh to a binary
// little-endian PLY file (vertex { x y z nx ny nz red green blue alpha },
// face { uchar list uint }) so a Blender artist can open the output of any
// pipeline phase by drag-and-drop. Used to capture the per-phase fascicle
// snapshot called out in the workspace plan.
//
// No dependency on EvoEngine asset machinery; works on a raw vertex/index
// pair so the same writer can be called from CLI tools, unit tests, or
// inside the live editor session.
// ---------------------------------------------------------------------------

#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <string>
#include <vector>

#include <glm/glm.hpp>

#include <Vertex.hpp>  // evo_engine::Vertex

namespace l_system_package {

inline bool WriteOrganMeshToPly(const std::filesystem::path& path, const std::vector<evo_engine::Vertex>& vertices,
                                const std::vector<glm::uvec3>& triangles) {
  std::FILE* fp = std::fopen(path.string().c_str(), "wb");
  if (!fp)
    return false;

  std::fprintf(fp, "ply\n");
  std::fprintf(fp, "format binary_little_endian 1.0\n");
  std::fprintf(fp, "comment Generated by EvoEngine LSystem Plugin (OrganMeshPly)\n");
  std::fprintf(fp, "element vertex %zu\n", vertices.size());
  std::fprintf(fp, "property float x\n");
  std::fprintf(fp, "property float y\n");
  std::fprintf(fp, "property float z\n");
  std::fprintf(fp, "property float nx\n");
  std::fprintf(fp, "property float ny\n");
  std::fprintf(fp, "property float nz\n");
  std::fprintf(fp, "property uchar red\n");
  std::fprintf(fp, "property uchar green\n");
  std::fprintf(fp, "property uchar blue\n");
  std::fprintf(fp, "property uchar alpha\n");
  std::fprintf(fp, "element face %zu\n", triangles.size());
  std::fprintf(fp, "property list uchar uint vertex_indices\n");
  std::fprintf(fp, "end_header\n");

  for (const auto& v : vertices) {
    const float pos[3] = {v.position.x, v.position.y, v.position.z};
    const float nrm[3] = {v.normal.x, v.normal.y, v.normal.z};
    auto to_byte = [](float c) -> std::uint8_t {
      const float clamped = c < 0.0f ? 0.0f : (c > 1.0f ? 1.0f : c);
      return static_cast<std::uint8_t>(clamped * 255.0f + 0.5f);
    };
    const std::uint8_t rgba[4] = {to_byte(v.color.r), to_byte(v.color.g), to_byte(v.color.b), to_byte(v.color.a)};
    std::fwrite(pos, sizeof(float), 3, fp);
    std::fwrite(nrm, sizeof(float), 3, fp);
    std::fwrite(rgba, sizeof(std::uint8_t), 4, fp);
  }
  for (const auto& t : triangles) {
    const std::uint8_t k = 3;
    const std::uint32_t idx[3] = {t.x, t.y, t.z};
    std::fwrite(&k, sizeof(std::uint8_t), 1, fp);
    std::fwrite(idx, sizeof(std::uint32_t), 3, fp);
  }

  std::fclose(fp);
  return true;
}

}  // namespace l_system_package