// @evoengine-dialect native
public struct Vertex {
  public float3 position;
  public float vertex_info1;
  public float3 normal;
  public float vertex_info2;
  public float3 tangent;
  public float vertex_info3;
  public float4 color;
  public float2 tex_coord;
  public float2 vertex_info4;
  public float2 tex_coord_1;
  public float2 tex_coord_2;
  public float2 tex_coord_3;
  public float2 padding;
};
