#pragma once
#include "ProceduralNoise.hpp"
#include "TreeDescriptor.hpp"

namespace eco_sys_lab_package {
using namespace evo_engine;

/**
 * \class BasicRootDescriptor
 * \brief Represents the parameters controlling procedural tree growth.
 *
 * This class defines various properties affecting tree shoot growth, including
 * internode characteristics, bud behavior, pruning, and environmental influences.
 */
class BasicRootDescriptor : public IRootDescriptor {
 public:
  /**
   * \brief The expected height gain for the tree for one year (max root distance).
   */
  float growth_rate = 0.25f;

  /**
   * \brief The factor influencing how straight the trunk grows.
   */
  float straight_tap_root = 0.0f;

  int base_root_node_count = 1;
  float lateral_node_flushing_probability;
  /**
   * \brief A procedural noise function affecting roll angles.
   */
  procedural_noise::ProceduralNoise4D branching_angle_graph{};
  /**
   * \brief A procedural noise function affecting roll angles.
   */
  procedural_noise::ProceduralNoise4D roll_angle_graph{};
  /**
   * \brief A procedural noise function affecting apical angles.
   */
  procedural_noise::ProceduralNoise4D apical_angle_graph{};

  /**
   * \brief The internode length.
   */
  float root_node_length = 0.03f;

  /**
   * \brief Factor by which branch thickness affects internode length.
   */
  float root_node_length_thickness_factor = 0.15f;

  /**
   * \brief Thickness of the end internode.
   */
  float end_node_thickness = 0.004f;

  /**
   * \brief Factor controlling thickness accumulation along the shoot.
   */
  float thickness_accumulation_factor = 0.45f;

  /**
   * \brief Additional thickness gained as the internode ages.
   */
  float thickness_age_factor = 0.0f;

  /**
   * \brief The strength of apical control over bud activation.
   */
  float apical_control = 0.f;

  /**
   * \brief The influence of root distance in determining bud fate.
   */
  float root_distance_control = 0.f;

  glm::vec2 soil_density_friction = glm::vec2(0.0f);
  /**
   * \brief Amount of inhibitor generated by an internode to suppress lateral growth.
   */
  float apical_dominance = 0.25f;

  /**
   * \brief Reduction of apical dominance as it propagates through the tree structure.
   */
  float apical_dominance_loss = 0.08f;

  float tropism_intensity;
  float tropism_switch_probability;
  float tropism_switch_base_distance_factor;

  /**
   * \brief Prepares a RootGrowthController using current growth parameters.
   * \param root_growth_controller The controller to configure.
   */
  void PrepareController(RootGrowthController& root_growth_controller) const override;

  /**
   * \brief Inspects and modifies shoot descriptor parameters in the editor.
   * \param editor_layer The editor layer providing UI interaction.
   * \return True if the asset's content remains unmodified.
   */
  bool DrawGui(const std::shared_ptr<EditorLayer>& editor_layer);
};
}  // namespace eco_sys_lab_package
