#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require
#extension GL_EXT_shader_atomic_float : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "AlphaShapeMeshing.glsl"
#include "VolumeMeasure.glsl"
#include "AlphaShapeVolumeMeasure.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;
const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PUSH_CONSTANTS {
  uint tetrahedron_size;
  uint frame_index;
  int padding0;
  int padding1;
};

void main() {
  [[unroll]]
  for (uint i = 0; i < ITERATIONS_PER_TASK; i++) {
    uint local_index = laneID + i * WORKGROUP_SIZE;
    uint tet_id = baseID + local_index;
    if (tet_id >= tetrahedron_size) {
      break;
    }
    float volume = MeasureAlphaTetrahedronVolume(tet_id);
    alpha_tet_current_volumes[tet_id] = volume;
    if (volume > 0.0) {
      atomicAdd(alpha_volume_result.cumulative_volume, volume);
    }
  }
}
