set(LSYSTEM_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
set(LSYSTEM_INCLUDES
	${LSYSTEM_DIRECTORY}
	${LSYSTEM_DIRECTORY}/include
	)
set(LSYSTEM_INCLUDES ${LSYSTEM_INCLUDES} PARENT_SCOPE)
file(GLOB_RECURSE LSYSTEM_HEADERS CONFIGURE_DEPENDS ${LSYSTEM_DIRECTORY}/include/*.hpp)
file(GLOB_RECURSE LSYSTEM_SOURCES CONFIGURE_DEPENDS ${LSYSTEM_DIRECTORY}/src/*.cpp)
list(APPEND LSYSTEM_SOURCES ${LSYSTEM_DIRECTORY}/src/ParamSpaceExplorer.cpp)
list(REMOVE_DUPLICATES LSYSTEM_SOURCES)

add_library(LSystemPlugin
	STATIC
	${LSYSTEM_HEADERS}
	${LSYSTEM_SOURCES}
	)
target_compile_definitions(LSystemPlugin
	PRIVATE
	${EVOENGINE_SDK_DEFS}
	${EVOENGINE_PLUGINS_DEFS}
	LSYSTEM_PLUGIN
	)
target_include_directories(LSystemPlugin
	PRIVATE
	${EVOENGINE_SDK_INCLUDES}
	${EVOENGINE_PLUGINS_INCLUDES}
	${LSYSTEM_INCLUDES}
	)
target_link_libraries(LSystemPlugin
	EvoEngine_SDK
	${EvoEngine_Plugins}
	)
set(LSYSTEM_PCH ${LSYSTEM_DIRECTORY}/include/LSystem_PCH.hpp)
set(LSYSTEM_PCH ${LSYSTEM_PCH} PARENT_SCOPE)

target_precompile_headers(LSystemPlugin
	PRIVATE
	${EVOENGINE_SDK_PCH}
	${EVOENGINE_PLUGINS_PCHS}
	${LSYSTEM_PCH}
	)

set(EVOENGINE_PLUGINS_INCLUDES ${EVOENGINE_PLUGINS_INCLUDES} ${LSYSTEM_INCLUDES} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_PCHS ${EVOENGINE_PLUGINS_PCHS} ${LSYSTEM_PCH} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_DEFS ${EVOENGINE_PLUGINS_DEFS} LSYSTEM_PLUGIN PARENT_SCOPE)
