#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

#include "Math.glsl"

const float PI = 3.1415926535897932384626433832795;

layout(push_constant) uniform PUSH_CONSTANTS {
	uint uniform_particle_size;
};

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint uniform_particle_index = baseID + local_index;

		if(uniform_particle_index >= uniform_particle_size) break;
		UniformParticle uniform_particle = uniform_particles[uniform_particle_index];

		// check if end of strand
		if(uniform_particle.is_on_surface == 2){
			uniform_particles[uniform_particle_index].is_on_surface = 0;
			continue;
		}

		// Initialize normal quaternion
		if(uniform_particle.normal_deg == vec4(0.0, 0.0, 0.0, 0.0)){
			uniform_particles[uniform_particle_index].normal_q = vec4(0.0, 0.0, 0.0, 0.0);
			continue;
		}

		uniform_particle.normal_deg.xyz = normalize(ProjectOntoPlane(uniform_particle.normal_deg.xyz, uniform_particle.tangent.xyz));
		Segment segment = segments[uniform_particle.segment_handle];
		vec3 up = rotate_vec3(segment.q0, vec3(0, 1, 0));

		// Compute the angle between the two vectors
		float angle = acos(dot(normalize(up), uniform_particle.normal_deg.xyz));
		uniform_particle.normal_deg.w = angle;
		vec3 axis = rotate_vec3(segment.q0, vec3(0, 0, 1));
		uniform_particle.normal_q = angle_axis(angle, axis);
		uniform_particle.is_on_surface = 1;
		uniform_particles[uniform_particle_index] = uniform_particle;
	}
}