#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER()        \
  memoryBarrierShared(); \
  barrier();

layout(std430, set = 1, binding = 0) readonly buffer EXTERNAL_FORCE_BLOCK {
  int segment_indices[];
};

layout(push_constant) uniform PUSH_CONSTANTS {
  vec4 target_position_multiplier;
  uint command_size;
};

void main() {
  [[unroll]]
  for (uint i = 0; i < ITERATIONS_PER_TASK; i++) {
    uint local_index = laneID + i * WORKGROUP_SIZE;
    uint global_index = baseID + local_index;

    if (global_index >= command_size)
      break;
    uint segment_index = uint(segment_indices[global_index]);
    Segment segment = segments[segment_index];
    vec3 force0 = (target_position_multiplier.xyz - segment.particle0.x) * target_position_multiplier.w;
    vec3 force1 = (target_position_multiplier.xyz - segment.particle1.x) * target_position_multiplier.w;

    segments[segment_index].particle0.acceleration.xyz += force0 * segment.inv_mass;
    segments[segment_index].particle1.acceleration.xyz += force1 * segment.inv_mass;
  }
}
