#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;
const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);
uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER()        \
  memoryBarrierShared(); \
  barrier();

layout(push_constant) uniform PC_APPLY {
  uint segment_size;
  float dt;
};

void clamp_and_apply(inout vec3 x, vec3 last_x, inout vec3 v, float ub, float dt, float scale) {
  float extra_cap = 0.0;
  float b = (extra_cap > 0.0) ? min(ub, extra_cap) : ub;
  vec3 dx = x - last_x;
  float l = length(dx);
  if (l > b && l > 0.0)
    dx *= (b / l);
  dx *= scale;
  x = last_x + dx;
  v = dx / dt;
}

void main() {
  [[unroll]]
  for (uint it = 0; it < ITERATIONS_PER_TASK; ++it) {
    uint local_index = laneID + it * WORKGROUP_SIZE;
    uint si = baseID + local_index;
    if (si >= segment_size)
      break;

    Segment s = segments[si];

    float scale = (s.quasi_stable == 1) ? s.ground_damping : 1.0;

    clamp_and_apply(s.particle0.x, s.particle0.last_x, s.particle0.v, s.particle0.user_bound, dt, scale);

    clamp_and_apply(s.particle1.x, s.particle1.last_x, s.particle1.v, s.particle1.user_bound, dt, scale);

    segments[si] = s;
  }
}
