#pragma once
#include "TreeDescriptor.hpp"

namespace eco_sys_lab_plugin {
using namespace evo_engine;

/**
 * \class BasicShootDescriptor
 * \brief Represents the parameters controlling procedural tree growth.
 *
 * This class defines various properties affecting tree shoot growth, including
 * internode characteristics, bud behavior, pruning, and environmental influences.
 */
class BasicShootDescriptor : public IShootDescriptor {
 public:
  /**
   * \brief The expected height gain for the tree for one year (max root distance).
   */
  float growth_rate = 0.25f;

  /**
   * \brief The factor influencing how straight the trunk grows.
   */
  float straight_trunk = 0.0f;

#pragma region Internode

  /**
   * \brief The number of base internodes in the shoot.
   */
  int base_internode_count = 1;
  /**
   * \brief A procedural noise function affecting roll angles.
   */
  procedural_noise::ProceduralNoise4D branching_angle_graph{};
  /**
   * \brief A procedural noise function affecting roll angles.
   */
  procedural_noise::ProceduralNoise4D roll_angle_graph{};
  /**
   * \brief A procedural noise function affecting apical angles.
   */
  procedural_noise::ProceduralNoise4D apical_angle_graph{};

  /**
   * \brief Influence of gravity on the shoot growth direction.
   */
  float gravitropism = 0.0;

  /**
   * \brief Influence of light direction on the shoot growth.
   */
  float phototropism = 0.045f;

  /**
   * \brief Influence of horizontal tropism on the tree's shape.
   */
  float horizontal_tropism = 0.0f;

  /**
   * \brief Strength of the gravity bending effect on the shoot.
   */
  float gravity_bending_strength = 0.f;

  /**
   * \brief Modifier for gravity bending based on thickness.
   */
  float gravity_bending_thickness_factor = 1.f;

  /**
   * \brief Maximum effect of gravity bending.
   */
  float gravity_bending_max = 1.f;

  /**
   * \brief The internode length.
   */
  float internode_length = 0.03f;

  /**
   * \brief Factor by which branch thickness affects internode length.
   */
  float internode_length_thickness_factor = 0.15f;

  /**
   * \brief Thickness of the end internode.
   */
  float end_node_thickness = 0.004f;

  /**
   * \brief Factor controlling thickness accumulation along the shoot.
   */
  float thickness_accumulation_factor = 0.45f;

  /**
   * \brief Additional thickness gained as the internode ages.
   */
  float thickness_age_factor = 0.0f;

  /**
   * \brief The effect of internode shadowing in the growth process.
   */
  float internode_shadow_factor = 0.03f;

#pragma endregion

#pragma region Bud fate

  /**
   * \brief The number of lateral buds an internode contains.
   */
  int lateral_bud_count = 1;

  /**
   * \brief The maximum branching order allowed (-1 means no limit).
   */
  int max_order = -1;

  /**
   * \brief The probability of apical bud dying each year.
   */
  float apical_bud_extinction_rate = 0.0f;

  /**
   * \brief The probability of lateral bud flushing each year.
   */
  float lateral_bud_flushing_rate = 0.5f;

  /**
   * \brief The strength of apical control over bud activation.
   */
  float apical_control = 0.f;

  /**
   * \brief The influence of root distance in determining bud fate.
   */
  float root_distance_control = 0.f;

  /**
   * \brief The effect of tree height on bud activation.
   */
  float height_control = 0.f;

  /**
   * \brief Amount of inhibitor generated by an internode to suppress lateral growth.
   */
  float apical_dominance = 0.25f;

  /**
   * \brief Reduction of apical dominance as it propagates through the tree structure.
   */
  float apical_dominance_loss = 0.08f;

  int conductance_model = 1;
  float pipe_model_exponent = 2.0f;
  float respiration_rate = 0.01f;
  float conductance_multiplier = 1.0f;

  bool pruning_force_sink_enabled = true;
  float pruning_force_sink_multiplier = 100.0f;
  int pruning_force_sink_depth = 0;
  float pruning_force_sink_depth_decay = 1.0f;

#pragma endregion

  /**
   * \brief Prepares a ShootGrowthController using current growth parameters.
   * \param shoot_growth_controller The controller to configure.
   */
  void PrepareController(ShootGrowthController& shoot_growth_controller) const override;

  /**
   * \brief Serializes the shoot descriptor to YAML format.
   * \param out The YAML emitter to write to.
   */
  void Serialize(YAML::Emitter& out) const override;

  /**
   * \brief Deserializes the shoot descriptor from YAML format.
   * \param in The YAML node containing serialized data.
   */
  void Deserialize(const YAML::Node& in) override;

  /**
   * \brief Inspects and modifies shoot descriptor parameters in the editor.
   * \param editor_layer The editor layer providing UI interaction.
   * \return True if the asset's content remains unmodified.
   */
  bool OnInspect(const std::shared_ptr<EditorLayer>& editor_layer) override;
};
}  // namespace eco_sys_lab_plugin