#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"
#include "SortCompare.glsl"

layout(local_size_x_id = 0) in; // Set value for local_size_x via specialization constant with id 0

layout(push_constant) uniform PUSH_CONSTANTS {
	uint segment_size;
	uint group_size;
};

// Workgroup local memory. We use this to minimise round-trips to global memory.
// It allows us to evaluate a sorting network of up to 1024 with one shader invocation.
shared HashedGridElement local_value[gl_WorkGroupSize.x * 2];

// Performs compare-and-swap over elements held in shared,
// workgroup-local memory
void local_compare_and_swap(ivec2 idx){
	if (COMPARE(local_value[idx.x], local_value[idx.y])) {
		HashedGridElement tmp = local_value[idx.x];
		local_value[idx.x] = local_value[idx.y];
		local_value[idx.y] = tmp;
	}
}

// Performs full-height flip (h height) over locally available indices.
void local_flip(in uint h){
	uint t = gl_LocalInvocationID.x;
	barrier();
	uint half_h = h >> 1; // Note: h >> 1 is equivalent to h / 2 
	ivec2 indices = 
		ivec2(h * ((2 * t) / h)) +
		ivec2(t % half_h, h - 1 - (t % half_h));
	local_compare_and_swap(indices);
}

// Performs progressively diminishing disperse operations (starting with height h)
// on locally available indices: e.g. h==8 -> 8 : 4 : 2.
// One disperse operation for every time we can divide h by 2.
void local_disperse(in uint h){
	uint t = gl_LocalInvocationID.x;
	for (; h > 1; h /= 2) {
		barrier();
		uint half_h = h >> 1; // Note: h >> 1 is equivalent to h / 2 
		ivec2 indices = 
			ivec2(h * ((2 * t) / h)) +
			ivec2(t % half_h, half_h + (t % half_h));
		local_compare_and_swap(indices);
	}
}

void main(){
	
	uint t = gl_LocalInvocationID.x;
 
 	// Calculate global offset for local workgroup
	uint offset = gl_WorkGroupSize.x * 2 * gl_WorkGroupID.x;
	uint segment_handle0 = offset + t * 2;
	uint segment_handle1 = offset + t * 2 + 1;

	// In case this shader executes a `local_` algorithm, we must 
	// first populate the workgroup's local memory.
	//
	if(segment_handle0 < segment_size) local_value[t * 2] = hashed_grid_elements[segment_handle0];
	else local_value[t * 2].cell_id = 0xFFFFFFFF;
	if(segment_handle1 < segment_size) local_value[t * 2 + 1] = hashed_grid_elements[segment_handle1];
	else local_value[t * 2 + 1].cell_id = 0xFFFFFFFF;

	// Perform binary merge sort for local elements, up to a maximum number 
	// of elements h.
	for (uint hh = 2; hh <= group_size; hh <<= 1) {  // note:  h <<= 1 is same as h *= 2
		local_flip(hh);
		local_disperse(hh / 2);
	}

	// Write local memory back to buffer in case we pulled in the first place.
	barrier();
	// push to global memory
	if(segment_handle0 < segment_size) hashed_grid_elements[segment_handle0] = local_value[t * 2];
	if(segment_handle1 < segment_size) hashed_grid_elements[segment_handle1] = local_value[t * 2 + 1];
}