#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER()        \
  memoryBarrierShared(); \
  barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint leaf_size;
        uint leaf_break_from_moisture;
        float leaf_break_threshold;
};

void main() {
  [[unroll]]
  for (uint i = 0; i < ITERATIONS_PER_TASK; i++) {
    uint local_index = laneID + i * WORKGROUP_SIZE;
    uint leaf_index = baseID + local_index;

    if (leaf_index >= leaf_size)
      break;

		Leaf leaf = foliage[leaf_index];
                Segment segment = segments[leaf.segment_handle];
                float multiplier = 1.0f;
                uint seed = leaf_index;
                float r = rand_ab(seed, 0.0, 0.4);
                if (leaf_break_from_moisture == 1) {
                  multiplier = clamp(
                      max(-r + segment.moisture_pre - leaf_break_threshold, 0.0) / (1.0 - leaf_break_threshold), 0.0f, 1.0f);
                }


		if(leaf.position_strain > leaf.position_strain_limit * multiplier){
			leaf.attachment_integrity = 0.0f;
			foliage[leaf_index] = leaf;
		}
                //if (leaf_break_from_moisture == 1) {
                //  if (segment.moisture_pre < leaf_break_threshold) {					  
                //    leaf.attachment_integrity = 0.0f;
                //    foliage[leaf_index] = leaf;
                //  }
                //}
	}
}