#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint pair_size;
	uint allow_disconnection;
	uint allow_breaking;
};

void main(){

	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint pair_index = baseID + local_index;
		if(pair_index >= pair_size) break;
		SegmentPair segment_pair = segment_pairs[pair_index];
		float connectivity_integrity = segment_pairs[pair_index].connectivity_integrity;
		float bend_twist_bundle_integrity = segment_pairs[pair_index].bend_twist_bundle_integrity;
		//Modify limit here.
		vec4 bending_twist_bundle_strain_limit = segment_pair.max_bending_twist_bundle_strain;
		vec4 bending_twist_bundle_strain = segment_pairs[pair_index].bending_twist_bundle_strain;

		int segment0_handle = segment_pairs[pair_index].segment0_handle;
		int segment1_handle = segment_pairs[pair_index].segment1_handle;

		if(allow_disconnection == 1){
			if(abs(segments[segment0_handle].shear_stretch_strain.x) > segments[segment0_handle].shear_stretch_strain_limit.x
				|| abs(segments[segment0_handle].shear_stretch_strain.y) > segments[segment0_handle].shear_stretch_strain_limit.y
				|| abs(segments[segment1_handle].shear_stretch_strain.x) > segments[segment1_handle].shear_stretch_strain_limit.x
				|| abs(segments[segment1_handle].shear_stretch_strain.y) > segments[segment1_handle].shear_stretch_strain_limit.y){
				connectivity_integrity = 0.0f;
			}
		}
		if(allow_breaking == 1){
			if(abs(bending_twist_bundle_strain.x) > bending_twist_bundle_strain_limit.x
				|| abs(bending_twist_bundle_strain.y) > bending_twist_bundle_strain_limit.y
				|| abs(bending_twist_bundle_strain.z) > bending_twist_bundle_strain_limit.z){
				bend_twist_bundle_integrity = 0.0f;
			}
		}

		segment_pairs[pair_index].bend_twist_bundle_integrity = bend_twist_bundle_integrity;
		segment_pairs[pair_index].connectivity_integrity = connectivity_integrity;
	}
}