#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint pair_size;
	uint allow_disconnection;
	uint allow_breaking;
	float compression_strength_factor;

    uint tensile_disconnection;
    uint compression_disconnection;
    uint positional_breaking;
    uint rotational_breaking;
};

void main(){

	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint pair_index = baseID + local_index;
		if(pair_index >= pair_size) break;
		SegmentPair segment_pair = segment_pairs[pair_index];
		float connectivity_integrity = segment_pairs[pair_index].connectivity_integrity;
		float bend_twist_bundle_integrity = segment_pairs[pair_index].bend_twist_bundle_integrity;
		vec3 bending_twist_bundle_strain_limit = segment_pair.bending_twist_bundle_strain_limit;
		vec3 bending_twist_bundle_strain = segment_pairs[pair_index].bending_twist_bundle_strain;

		float connectivity_strain_limit = segment_pair.connectivity_strain_limit;
		float connectivity_strain = segment_pairs[pair_index].connectivity_strain;


		int segment0_handle = segment_pairs[pair_index].segment0_handle;
		int segment1_handle = segment_pairs[pair_index].segment1_handle;

		bool is_connection = segment_pairs[pair_index].connectivity_integrity != 0.f && (segments[segment0_handle].next_handle == segment1_handle || segments[segment1_handle].next_handle == segment0_handle);
		
		if(allow_disconnection == 1){
			if(((tensile_disconnection == 1 && segment_pairs[pair_index].tensile_lock == 0) && connectivity_strain > connectivity_strain_limit)
				|| ((compression_disconnection == 1 && segment_pairs[pair_index].compression_lock == 0) && connectivity_strain < -connectivity_strain_limit * compression_strength_factor)
				){
				connectivity_integrity = 0.0f;
			}
		}
		if(allow_breaking == 1){
			if(is_connection){
				if(((positional_breaking == 1 && segment_pairs[pair_index].positional_lock == 0) && (abs(segments[segment0_handle].shear_stretch_strain) > segments[segment0_handle].shear_stretch_strain_limit
						|| abs(segments[segment1_handle].shear_stretch_strain) > segments[segment1_handle].shear_stretch_strain_limit))

					|| ((rotational_breaking == 1 && segment_pairs[pair_index].rotational_lock == 0) && (abs(bending_twist_bundle_strain.x) > bending_twist_bundle_strain_limit.x
						|| abs(bending_twist_bundle_strain.y) > bending_twist_bundle_strain_limit.y))
					){
					bend_twist_bundle_integrity = 0.0f;
				}
			}else{
				bool bundle_breaking = false;
				bundle_breaking = bundle_breaking || ((tensile_disconnection == 1 && segment_pairs[pair_index].tensile_lock == 0) && bending_twist_bundle_strain.z > bending_twist_bundle_strain_limit.z);
				bundle_breaking = bundle_breaking || ((compression_disconnection == 1 && segment_pairs[pair_index].compression_lock == 0) && bending_twist_bundle_strain.z < -bending_twist_bundle_strain_limit.z * compression_strength_factor);

				if(((rotational_breaking == 1 && segment_pairs[pair_index].rotational_lock == 0) && (abs(bending_twist_bundle_strain.x) > bending_twist_bundle_strain_limit.x
						|| abs(bending_twist_bundle_strain.y) > bending_twist_bundle_strain_limit.y))
					|| ((positional_breaking == 1 && segment_pairs[pair_index].positional_lock == 0) && bundle_breaking)
					){
					bend_twist_bundle_integrity = 0.0f;
				}
			}
			
		}

		segment_pairs[pair_index].bend_twist_bundle_integrity = bend_twist_bundle_integrity;
		segment_pairs[pair_index].connectivity_integrity = connectivity_integrity;
	}
}