#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	vec3 max_angular_velocity;
	float time_step;
	vec3 max_velocity;
	float inv_time_step;

	uint leaf_size;
};

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint leaf_index = baseID + local_index;

		if(leaf_index >= leaf_size) break;

		Leaf leaf = foliage[leaf_index];

		//Calculate angular velocity and apply torque.
		vec3 angular_velocity = vec3(0, 0, 0);
		vec3 velocity = vec3(0.0f, 0.0f, 0.0f);
		if(leaf.inv_mass != 0.0f){
			vec4 rot = quat_mul(leaf.q, conjugate(leaf.last_q));
			angular_velocity = rot.xyz * 2.0f * inv_time_step;
			velocity = inv_time_step * (leaf.x - leaf.last_x);
		}

		foliage[leaf_index].angular_v = min(inv_time_step * max_angular_velocity, angular_velocity);
		foliage[leaf_index].v = min(inv_time_step * max_velocity, velocity);
	}
}