#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER()        \
  memoryBarrierShared(); \
  barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
  vec3 max_angular_velocity;
  float time_step;
  vec3 max_velocity;
  float inv_time_step;

  uint segment_size;
  float angular_velocity_damping;
  float velocity_damping;
};

void main() {
  [[unroll]]
  for (uint i = 0; i < ITERATIONS_PER_TASK; i++) {
    uint local_index = laneID + i * WORKGROUP_SIZE;
    uint segment_index = baseID + local_index;

    if (segment_index >= segment_size)
      break;

    Segment segment = segments[segment_index];
    update_inertia_w(segment.q, segment.inertia_tensor, segment.inv_inertia_tensor, segment.inertia_w,
                     segment.inv_inertia_w);

    // Calculate angular velocity and apply torque.
    vec3 angular_velocity = vec3(0, 0, 0);
    vec3 p0_velocity = vec3(0.0f, 0.0f, 0.0f);
    vec3 p1_velocity = vec3(0.0f, 0.0f, 0.0f);
    if (segment.inv_mass != 0.0f) {
      vec4 rot = quat_mul(segment.q, conjugate(segment.last_q));
      angular_velocity = rot.xyz * 2.0f * inv_time_step;
      p0_velocity = inv_time_step * (segment.particle0.x - segment.particle0.last_x);
      p1_velocity = inv_time_step * (segment.particle1.x - segment.particle1.last_x);

      angular_velocity *= max(0.f, 1.f - angular_velocity_damping * length(angular_velocity) * time_step);
      angular_velocity += time_step * mat3(segment.inv_inertia_w) *
                          (segment.torque - cross(angular_velocity, mat3(segment.inertia_w) * angular_velocity));

      p0_velocity *= max(0.f, 1.f - velocity_damping * length(p0_velocity) * time_step);
      p0_velocity += segment.particle0.acceleration.xyz * time_step;

      p1_velocity *= max(0.f, 1.f - velocity_damping * length(p1_velocity) * time_step);
      p1_velocity += segment.particle1.acceleration.xyz * time_step;
    }

    segments[segment_index].angular_v = min(max_angular_velocity, angular_velocity);
    segments[segment_index].particle0.v = min(max_velocity, p0_velocity);
    segments[segment_index].particle1.v = min(max_velocity, p1_velocity);

    vec3 up = vec3(0.0, 1.0, 0.0);
    vec3 down = vec3(0.0, -1.0, 0.0);
    float friction = 0.8 * 9.8;
    if (segments[segment_index].reach_ground == 1) {  // Todo: Enhanced Friction Model
      segments[segment_index].particle0.v = scaleAlongDirectional(segments[segment_index].particle0.v, up, 0.1);
      segments[segment_index].particle1.v = scaleAlongDirectional(segments[segment_index].particle1.v, up, 0.1);

      // if (segments[segment_index].particle0.padding1 == 0)
      //       {
      //                  segments[segment_index].particle0.v =
      //                      scaleAlongDirectional(segments[segment_index].particle0.v, up, 0.02);
      //    segments[segment_index].particle0.padding1 = 1;
      //}
      //              if (segments[segment_index].particle1.padding1 == 0)
      //{
      //    segments[segment_index].particle1.v =
      //                    scaleAlongDirectional(segments[segment_index].particle1.v, up, 0.02);
      //                  segments[segment_index].particle1.padding1 = 1;
      //}
      segments[segment_index].particle1.acceleration -=
          length(vec3(segments[segment_index].particle1.v.x, segments[segment_index].particle1.v.y, 0.f)) > 1e-9f
              ? normalize(segments[segment_index].particle1.v) * friction
              : vec3(0.0);
      segments[segment_index].particle0.acceleration -=
          length(vec3(segments[segment_index].particle0.v.x, segments[segment_index].particle0.v.y, 0.f)) > 1e-9f
              ? normalize(segments[segment_index].particle0.v) * friction
              : vec3(0.0);
    }
    /*if (segments[segment_index].quasi_stable == 1) {
      segments[segment_index].particle0.v =
          scaleAlongDirectional(segments[segment_index].particle0.v, down, 0.2);
      segments[segment_index].particle1.v =
          scaleAlongDirectional(segments[segment_index].particle1.v, down, 0.2);
    }*/
  }
}