#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	vec4 obb_center;
	float radius;
	float softness;
	uint segment_size;
};

vec3 process_point(in vec3 p){
	vec3 projected_p = p - obb_center.xyz;
	float current_radius = length(projected_p);
	if(current_radius == 0.0f) return obb_center.xyz + radius * vec3(0, 1, 0);
	return obb_center.xyz + max(current_radius, radius) * normalize(projected_p);
}

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint segment_index = baseID + local_index;

		if(segment_index >= segment_size) break;

		Segment segment = segments[segment_index];
		int particle0_handle = segment.particle_0_handle;
		int particle1_handle = segment.particle_1_handle;
		Particle particle0 = particles[particle0_handle];
		Particle particle1 = particles[particle1_handle];

		vec3 p0 = particle0.x;
		vec3 p1 = particle1.x;

		p0 = process_point(p0);
		p1 = process_point(p1);

		particles[particle0_handle].x = p0;
		particles[particle1_handle].x = p1;
	}
}