#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER()        \
  memoryBarrierShared(); \
  barrier();

struct SegmentUpdate {
  float point_distance;
  uint segment_index;
  uint padding0;
  uint padding1;
};

layout(std430, set = 1, binding = 0) readonly buffer SEGMENT_UPDATE_BLOCK {
  SegmentUpdate segment_updates[];
};

layout(push_constant) uniform PUSH_CONSTANTS {
  vec3 pivot_position;
  uint command_size;
};

void main() {
  [[unroll]]
  for (uint i = 0; i < ITERATIONS_PER_TASK; i++) {
    uint local_index = laneID + i * WORKGROUP_SIZE;
    uint global_index = baseID + local_index;

    if (global_index >= command_size)
      break;

    SegmentUpdate segment_update = segment_updates[global_index];
    uint segment_index = segment_update.segment_index;
    Segment segment = segments[segment_index];
    vec3 front_direction = normalize(rotate_vec3(segment.q, vec3(0, 0, -1)));

    float current_segment_length = distance(segment.particle0.x, segment.particle1.x);
    vec3 segment_center_position = (segment.particle0.x + segment.particle1.x) * 0.5f;

    vec3 diff = segment_center_position - pivot_position;
    vec3 direction = length(diff) == 0.0f ? front_direction : normalize(diff);

    vec3 desired_segment_center_position = pivot_position + segment_update.point_distance * direction;

    vec3 offset = front_direction * 0.5f * current_segment_length;
    segment.particle0.x = segment.particle0.last_x = desired_segment_center_position - offset;
    segment.particle1.x = segment.particle1.last_x = desired_segment_center_position + offset;
    segments[segment_index] = segment;
  }
}