#extension GL_ARB_shading_language_include : enable

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 1, binding = 17) uniform sampler2D inDepth;

layout(set = 0, binding = 0) uniform sampler2D image;
layout(set = 0, binding = 1, r16f) uniform writeonly image2D outImage;

layout(push_constant) uniform BLUR_CONSTANTS {
  int horizontal;
  float camera_near;
  float camera_far;
  float avoid_distance;
  float weight[5];
};

float LinearizeDepth(float ndcDepth) {
  return camera_near * camera_far / (camera_far - ndcDepth * (camera_far - camera_near));
}

void main() {
  uvec2 pixel = gl_GlobalInvocationID.xy;
  uvec2 resolution = uvec2(imageSize(outImage));
  if (pixel.x >= resolution.x || pixel.y >= resolution.y) {
    return;
  }

  vec2 texCoord = (vec2(pixel) + vec2(0.5f)) / vec2(resolution);
  vec2 texOffset = 1.0 / textureSize(image, 0);
  vec4 current = texture(image, texCoord).rgba;
  vec4 result = current * weight[0];
  float depth = LinearizeDepth(texture(inDepth, texCoord).x);

  if (horizontal != 0) {
    for (int i = 1; i < 5; ++i) {
      vec2 coord1 = texCoord + vec2(texOffset.x * i, 0.0);
      float depth1 = LinearizeDepth(texture(inDepth, coord1).x);
      result += abs(depth1 - depth) < avoid_distance ? texture(image, coord1).rgba * weight[i] : current * weight[i];

      vec2 coord2 = texCoord - vec2(texOffset.x * i, 0.0);
      float depth2 = LinearizeDepth(texture(inDepth, coord2).x);
      result += abs(depth2 - depth) < avoid_distance ? texture(image, coord2).rgba * weight[i] : current * weight[i];
    }
  } else {
    for (int i = 1; i < 5; ++i) {
      vec2 coord1 = texCoord + vec2(0.0, texOffset.y * i);
      float depth1 = LinearizeDepth(texture(inDepth, coord1).x);
      result += abs(depth1 - depth) < avoid_distance ? texture(image, coord1).rgba * weight[i] : current * weight[i];

      vec2 coord2 = texCoord - vec2(0.0, texOffset.y * i);
      float depth2 = LinearizeDepth(texture(inDepth, coord2).x);
      result += abs(depth2 - depth) < avoid_distance ? texture(image, coord2).rgba * weight[i] : current * weight[i];
    }
  }

  imageStore(outImage, ivec2(pixel), result);
}
