layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(push_constant) uniform EE_BLOOM_MIX_CONSTANTS {
  uvec2 resolution;
};

layout(set = 0, binding = 0) uniform sampler2D originalColor;
layout(set = 0, binding = 1) uniform sampler2D bloomColor;
layout(set = 0, binding = 2, rgba32f) uniform writeonly image2D outColor;

void main() {
  uvec2 pixel = gl_GlobalInvocationID.xy;
  if (pixel.x >= resolution.x || pixel.y >= resolution.y) {
    return;
  }

  ivec2 texel = ivec2(pixel);
  vec4 color = texelFetch(originalColor, texel, 0);
  vec4 bloom = texelFetch(bloomColor, texel, 0);
  imageStore(outColor, texel, vec4(clamp(color.xyz, vec3(0.0f), vec3(1.0f)) + bloom.xyz, color.w));
}
