#extension GL_ARB_shading_language_include : enable

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D originalColor;
layout(set = 0, binding = 1) uniform sampler2D ambientOcclusion;
layout(set = 1, binding = 0, rgba32f) uniform writeonly image2D outColor;

void main() {
  uvec2 pixel = gl_GlobalInvocationID.xy;
  uvec2 resolution = uvec2(imageSize(outColor));
  if (pixel.x >= resolution.x || pixel.y >= resolution.y) {
    return;
  }

  vec2 texCoord = (vec2(pixel) + vec2(0.5f)) / vec2(resolution);
  vec4 color = texture(originalColor, texCoord);
  vec3 result = color.rgb * texture(ambientOcclusion, texCoord).r;
  imageStore(outColor, ivec2(pixel), vec4(result, color.a));
}
