#extension GL_ARB_shading_language_include : enable

#include "PerFrame.glsl"
#include "VogelDisk.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 1, binding = 17) uniform sampler2D inDepth;
layout(set = 1, binding = 18) uniform sampler2D inNormal;
layout(set = 1, binding = 19) uniform sampler2D inMaterial;
layout(set = 2, binding = 0) uniform sampler2D inColor;
layout(set = 3, binding = 0, rgba32f) uniform writeonly image2D outSrcColor;
layout(set = 3, binding = 1, rgba32f) uniform writeonly image2D outAmbientOcclusion;

layout(push_constant) uniform EE_SSAO_CONSTANTS {
  int EE_CAMERA_INDEX;
  int kernelSize;
  float radius;
  float bias;
  float factor;
  float intensity;
};

vec3 GetNormal(in vec2 texCoord) {
  return texture(inNormal, texCoord).rgb;
}

vec3 GetViewNormal(in vec2 texCoord) {
  return normalize((EE_CAMERAS[EE_CAMERA_INDEX].view * vec4(GetNormal(texCoord), 0.0f)).xyz);
}

bool GetViewPosition(in vec2 texCoord, out vec3 position) {
  float ndcDepth = texture(inDepth, texCoord).x;
  if (ndcDepth == 1.0f) {
    return false;
  }
  position = EE_DEPTH_TO_VIEW_POS(EE_CAMERA_INDEX, texCoord, ndcDepth);
  return true;
}

void main() {
  uvec2 pixel = gl_GlobalInvocationID.xy;
  uvec2 resolution = uvec2(imageSize(outSrcColor));
  if (pixel.x >= resolution.x || pixel.y >= resolution.y) {
    return;
  }

  vec2 texCoord = (vec2(pixel) + vec2(0.5f)) / vec2(resolution);
  imageStore(outSrcColor, ivec2(pixel), texture(inColor, texCoord));

  vec3 viewPos;
  if (!GetViewPosition(texCoord, viewPos)) {
    imageStore(outAmbientOcclusion, ivec2(pixel), vec4(1, 1, 1, 1));
    return;
  }

  vec3 normal = GetViewNormal(texCoord);
  vec3 randomVec = EE_UNIFORM_KERNEL[int(EE_INTERLEAVED_GRADIENT_NOISE(viewPos * 3141) * MAX_KERNEL_AMOUNT) %
                                     MAX_KERNEL_AMOUNT]
                       .xyz;
  mat4 projection = EE_CAMERAS[EE_CAMERA_INDEX].projection;

  vec3 tangent = normalize(randomVec - normal * dot(randomVec, normal));
  vec3 bitangent = cross(normal, tangent);
  mat3 TBN = mat3(tangent, bitangent, normal);
  float occlusion = 0.0f;
  for (int i = 0; i < kernelSize; ++i) {
    vec3 point = EE_UNIFORM_KERNEL[i].xyz;
    point.z = abs(point.z);
    vec3 samplePos = TBN * point;
    samplePos = viewPos + samplePos * radius;
    vec4 offset = vec4(samplePos, 1.0f);
    offset = projection * offset;
    offset.xyz /= offset.w;
    offset.xyz = offset.xyz * 0.5f + 0.5f;

    vec3 sampleViewPos;
    if (!GetViewPosition(offset.xy, sampleViewPos)) {
      continue;
    }
    float sampleDepth = sampleViewPos.z;
    float rangeCheck = smoothstep(0.0f, 1.0f, pow((radius - distance(viewPos, sampleViewPos)) / radius, factor));
    occlusion += (sampleDepth >= (samplePos.z + bias) ? 1.0f : 0.0f) * rangeCheck;
  }

  imageStore(outAmbientOcclusion, ivec2(pixel), vec4(max(0.0f, 1.0f - occlusion / kernelSize * intensity)));
}
