#extension GL_ARB_shading_language_include : enable

#define EE_MATERIALS_BLOCK_SET 0
#define EE_MATERIALS_BLOCK_BINDING 3
#include "Materials.glsl"
#include "SSRConstants.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 1, binding = 0) uniform sampler2D originalColor;
layout(set = 1, binding = 1) uniform sampler2D reflectedColorVisibility;
layout(set = 2, binding = 17) uniform sampler2D inDepth;
layout(set = 2, binding = 18) uniform sampler2D inNormal;
layout(set = 2, binding = 19) uniform sampler2D inMaterial;
layout(set = 3, binding = 0, rgba32f) uniform writeonly image2D outColor;

void main() {
  uvec2 pixel = gl_GlobalInvocationID.xy;
  uvec2 resolution = uvec2(imageSize(outColor));
  if (pixel.x >= resolution.x || pixel.y >= resolution.y) {
    return;
  }

  vec2 texCoord = (vec2(pixel) + vec2(0.5f)) / vec2(resolution);
  int material_index = int(round(texture(inMaterial, texCoord).w));
  MaterialProperties materialProperties = EE_MATERIAL_PROPERTIES[material_index];

  float roughness = materialProperties.roughness;
  float metallic = materialProperties.metallic;

  vec4 color = texture(originalColor, texCoord);
  vec4 reflected = texture(reflectedColorVisibility, texCoord);

  float factor = clamp(reflected.a * metallic * (1.f - roughness), 0.0f, 1.0f);
  vec3 result = color.xyz * (1.0f - factor) + reflected.rgb * factor;
  imageStore(outColor, ivec2(pixel), vec4(result.xyz, color.w));
}
