#extension GL_ARB_shading_language_include : enable

#include "SSRConstants.glsl"
#include "PerFrame.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 1, binding = 17) uniform sampler2D inDepth;
layout(set = 1, binding = 21) uniform sampler2D inNormalRoughness;
layout(set = 2, binding = 0) uniform sampler2D inColor;
layout(set = 3, binding = 0, rgba32f) uniform writeonly image2D outSrcColor;
layout(set = 3, binding = 1, rgba32f) uniform writeonly image2D outDstColorVisibility;

vec3 GetNormal(in vec2 texCoord) {
  return texture(inNormalRoughness, texCoord).rgb;
}

vec3 GetViewNormal(in vec2 texCoord) {
  return normalize((EE_CAMERAS[EE_CAMERA_INDEX].view * vec4(GetNormal(texCoord), 0.0f)).xyz);
}

bool GetViewPosition(in vec2 texCoord, out vec3 position) {
  float ndcDepth = texture(inDepth, texCoord).x;
  if (ndcDepth == 1.0f) {
    return false;
  }
  position = EE_DEPTH_TO_VIEW_POS(EE_CAMERA_INDEX, texCoord, ndcDepth);
  return true;
}

void main() {
  uvec2 pixel = gl_GlobalInvocationID.xy;
  uvec2 resolution = uvec2(imageSize(outSrcColor));
  if (pixel.x >= resolution.x || pixel.y >= resolution.y) {
    return;
  }

  vec2 texSize = vec2(resolution);
  vec2 texCoord = (vec2(pixel) + vec2(0.5f)) / texSize;
  vec4 srcColor = texture(inColor, texCoord);
  imageStore(outSrcColor, ivec2(pixel), srcColor);

  int steps = initial_steps;
  vec2 uv = vec2(0.0);
  vec3 positionFrom;

  if (!GetViewPosition(texCoord, positionFrom)) {
    imageStore(outDstColorVisibility, ivec2(pixel), vec4(0, 0, 0, 0));
    return;
  }
  vec3 positionTo = positionFrom;

  vec3 unitPositionFrom = normalize(positionFrom.xyz);
  vec3 normal = GetViewNormal(texCoord);
  vec3 pivot = normalize(reflect(unitPositionFrom, normal));

  vec4 startView = vec4(positionFrom.xyz + (pivot * 0), 1);
  vec4 endView = vec4(positionFrom.xyz + (pivot * max_distance), 1);

  vec4 startFragTemp = EE_CAMERAS[EE_CAMERA_INDEX].projection * startView;
  startFragTemp.xyz /= startFragTemp.w;
  startFragTemp.xy = startFragTemp.xy * 0.5f + 0.5f;

  vec4 endFragTemp = EE_CAMERAS[EE_CAMERA_INDEX].projection * endView;
  endFragTemp.xyz /= endFragTemp.w;
  endFragTemp.xy = endFragTemp.xy * 0.5f + 0.5f;

  vec2 startFrag = startFragTemp.xy;
  vec2 endFrag = endFragTemp.xy;
  float useX = 0.0;

  startFrag *= texSize;
  endFrag *= texSize;

  vec2 frag = startFrag;
  uv = frag / texSize;

  float deltaX = endFrag.x - startFrag.x;
  float deltaY = endFrag.y - startFrag.y;
  vec2 increment = vec2(deltaX, deltaY) / iteration_count;
  float search0 = 0;
  float search1 = 0;

  int hit0 = 0;
  int hit1 = 0;

  float viewDistance = startView.z;
  float depth = thickness;

  float i = 0;

  for (i = 0; i < iteration_count; ++i) {
    frag += increment;
    uv = frag / texSize;
    GetViewPosition(uv, positionTo);

    search1 = mix((frag.y - startFrag.y) / deltaY, (frag.x - startFrag.x) / deltaX, useX);
    search1 = clamp(search1, 0.0, 1.0);

    viewDistance = (startView.z * endView.z) / mix(endView.z, startView.z, search1);
    depth = positionTo.z - viewDistance;

    if (depth > 0 && depth < thickness) {
      hit0 = 1;
      break;
    } else {
      search0 = search1;
    }
  }

  search1 = search0 + ((search1 - search0) / 2.0);
  steps *= hit0;

  for (i = 0; i < steps; ++i) {
    frag = mix(startFrag.xy, endFrag.xy, search1);
    uv.xy = frag / texSize;
    GetViewPosition(uv, positionTo);

    viewDistance = (startView.z * endView.z) / mix(endView.z, startView.z, search1);
    depth = positionTo.z - viewDistance;

    if (depth > 0 && depth < thickness) {
      hit1 = 1;
      search1 = search0 + ((search1 - search0) / 2);
    } else {
      float temp = search1;
      search1 = search1 + ((search1 - search0) / 2);
      search0 = temp;
    }
  }

  float visibility = hit1 * (1 - max(dot(-unitPositionFrom, pivot), 0)) * (1 - clamp(depth / thickness, 0, 1)) *
                     (1 - pow(clamp(length(positionTo - positionFrom) / max_distance, 0, 1), distance_confidence)) *
                     (uv.x < 0 || uv.x > 1 ? 0 : 1) * (uv.y < 0 || uv.y > 1 ? 0 : 1);

  visibility = clamp(visibility, 0, 1);

  if (visibility != 0) {
    imageStore(outDstColorVisibility, ivec2(pixel), max(vec4(texture(inColor, uv).rgb, visibility), vec4(0.0f)));
  } else {
    imageStore(outDstColorVisibility, ivec2(pixel), vec4(0, 0, 0, 0));
  }
}
