layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D inColor;
layout(set = 0, binding = 1, rgba32f) uniform writeonly image2D outColor;

void main() {
  uvec2 pixel = gl_GlobalInvocationID.xy;
  uvec2 resolution = uvec2(imageSize(outColor));
  if (pixel.x >= resolution.x || pixel.y >= resolution.y) {
    return;
  }

  ivec2 texel = ivec2(pixel);
  imageStore(outColor, texel, texelFetch(inColor, texel, 0));
}
