set(PROCEDURAL_NOISE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})

set(PROCEDURAL_NOISE_INCLUDES
	${PROCEDURAL_NOISE_DIRECTORY}/include
	)
file(GLOB_RECURSE PROCEDURAL_NOISE_HEADERS ${PROCEDURAL_NOISE_DIRECTORY}/include/*.hpp)
file(GLOB_RECURSE PROCEDURAL_NOISE_SOURCES ${PROCEDURAL_NOISE_DIRECTORY}/src/*.cpp)

add_library(ProceduralNoisePlugin
	STATIC
	${PROCEDURAL_NOISE_HEADERS}
	${PROCEDURAL_NOISE_SOURCES}
	)
target_compile_definitions(ProceduralNoisePlugin
	PRIVATE
	${EVOENGINE_SDK_DEFS}
	${EVOENGINE_PLUGINS_DEFS}
	)	
target_include_directories(ProceduralNoisePlugin
	PRIVATE
	${EVOENGINE_SDK_INCLUDES}
	${EVOENGINE_PLUGINS_INCLUDES}
	${PROCEDURAL_NOISE_INCLUDES}
	)
target_link_libraries(ProceduralNoisePlugin
	EvoEngine_SDK
	${EvoEngine_Plugins}
	)
set(PROCEDURAL_NOISE_PCH ${PROCEDURAL_NOISE_DIRECTORY}/include/ProceduralNoise_PCH.hpp)
set(PROCEDURAL_NOISE_PCH ${PROCEDURAL_NOISE_PCH} PARENT_SCOPE)

target_precompile_headers(ProceduralNoisePlugin
	PRIVATE
	${EVOENGINE_SDK_PCH}
	${EVOENGINE_PLUGINS_PCHS}
	${PROCEDURAL_NOISE_PCH}
	)

set(EVOENGINE_PLUGINS_INCLUDES ${EVOENGINE_PLUGINS_INCLUDES} ${PROCEDURAL_NOISE_INCLUDES} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_PCHS ${EVOENGINE_PLUGINS_PCHS} ${PROCEDURAL_NOISE_PCH} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_DEFS ${EVOENGINE_PLUGINS_DEFS} PROCEDURAL_NOISE_PLUGIN PARENT_SCOPE)
