#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint leaf_size;
};


void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint leaf_index = baseID + local_index;
		if(leaf_index >= leaf_size) break;
		Leaf leaf = foliage[leaf_index];
		if(leaf.attachment_integrity != 0.0f){
			Segment segment = segments[leaf.segment_handle];
			vec3 segment_center_position =
				(segment.particle0.x + segment.particle1.x) * 0.5f;
			vec3 position_correction = segment_center_position + rotate_vec3(segment.q, leaf.position_offset) - leaf.x;
			position_correction /= 1.f + leaf.position_alpha;
			leaf.x += position_correction;
			leaf.q = quat_mul(segment.q, quat_mul(conjugate(segment.q0), leaf.q0));
		}
		foliage[leaf_index] = leaf;
	}
}