#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = EXT_TASK_SUBGROUP_COUNT * EXT_TASK_SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((EXT_INVOCATIONS_PER_TASK + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * EXT_INVOCATIONS_PER_TASK;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint particle_size;
};

struct ParticleNeighbor{
	vec4 new_position;
	int neighbors[8];
	vec4 offset[8];
};

layout(std430, set = 1, binding = 0) buffer CONNECTIVITY_BLOCK {
  ParticleNeighbor particle_neighbors[];
};

void main(){

	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint particle_index = baseID + local_index;

		if(particle_index >= particle_size) break;

		Particle particle = particles[particle_index];
		ParticleNeighbor particle_neighbor = particle_neighbors[particle_index];
		vec3 movement = vec3(0.0, 0.0, 0.0);
		int sum = 0;
		float distance_diff_sum = 0.0;
		[[unroll]]
		for(uint n_i = 0; n_i < 8; n_i++){
			int neighbor_particle_index = particle_neighbor.neighbors[n_i];
			if(neighbor_particle_index == -1) continue;
			vec3 neighbor_position = particles[neighbor_particle_index].x_node_handle.xyz;
			//float current_distance = distance(neighbor_position, particle.x_node_handle.xyz);
			//vec3 direction = normalize(neighbor_position - particle.x_node_handle.xyz);
			//distance_diff_sum += abs(current_distance - particle_neighbor.offset[n_i].w);
			//movement += direction * (current_distance - particle_neighbor.offset[n_i].w) * 0.5;
			vec3 current_offset = particle.x_node_handle.xyz - neighbor_position;
			vec3 diff = particle_neighbor.offset[n_i].xyz - current_offset;
			float local_connectivity_strain = abs(length(diff));
			if(local_connectivity_strain < 1.0){
				distance_diff_sum += local_connectivity_strain;
				movement += diff;
				sum += 1;
			}else{
				particle_neighbor.neighbors[n_i] = -1;
			}
		}
		if(sum != 0){ 
			particle_neighbors[particle_index].new_position.xyz = particle.x_node_handle.xyz + movement / sum;
			particles[particle_index].acceleration_connectivity_strain.w = distance_diff_sum / sum;
		}
		else{ 
			particle_neighbors[particle_index].new_position.xyz = particle.x_node_handle.xyz;
			particles[particle_index].acceleration_connectivity_strain.w = 0.0;
		}
	}
}