#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"
const uint WORKGROUP_SIZE = EXT_TASK_SUBGROUP_COUNT * EXT_TASK_SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((EXT_INVOCATIONS_PER_TASK + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * EXT_INVOCATIONS_PER_TASK;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint segment_size;
	float inv_time_step;
};

#include "RandomBundle.glsl"


void main(){

	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint segment_index = baseID + local_index;
		if(segment_index >= segment_size) break;
		Segment segment = segments[segment_index];
		int particle0_handle = floatBitsToInt(segment.inertia_tensor_particle_0_handle.w);
		int particle1_handle = floatBitsToInt(segment.inv_inertia_tensor_particle_1_handle.w);
		float max_strain0 = 0.0;
		float max_strain1 = 0.0;
		if(segment.inv_mass == 0.0) {
			segment_data_list[segment_index].particle0_position_correction_max_strain.xyz = vec3(0.0, 0.0, 0.0);
			segment_data_list[segment_index].particle1_position_correction_max_strain.xyz = vec3(0.0, 0.0, 0.0);
			segment_data_list[segment_index].q_correction = vec4(0.0, 0.0, 0.0, 0.0);

			particles[particle0_handle].acceleration_connectivity_strain.w = max_strain0;
			particles[particle1_handle].acceleration_connectivity_strain.w = max_strain1;

			continue;
		}

		SegmentData segment_data = segment_data_list[segment_index];

		vec3 movement0 = vec3(0.0, 0.0, 0.0);
		vec3 movement1 = vec3(0.0, 0.0, 0.0);

		vec4 q_correction = vec4(0.0, 0.0, 0.0, 0.0);

		int sum = 0;
		[[unroll]]
		for(uint pair_index = 0; pair_index < BUNDLE_MAX_CONNECTION; pair_index++){
			int pair_handle = segment_data.pair_handles[pair_index];
			if(pair_handle == -1) continue;
			SegmentPair segment_pair = segment_pairs[pair_handle];
			if(segment_pair.valid == 0) continue; //line 68

			int neighbor_handle = segment_pair.handle0 == segment_index ? segment_pair.handle1 : segment_pair.handle0;
			Segment neighbor_segment = segments[neighbor_handle];
			vec3 neighbor_segment_particle0_position = particles[floatBitsToInt(neighbor_segment.inertia_tensor_particle_0_handle.w)].x_node_handle.xyz;
			vec3 neighbor_segment_particle1_position = particles[floatBitsToInt(neighbor_segment.inv_inertia_tensor_particle_1_handle.w)].x_node_handle.xyz;

			vec3 neighbor_segment_center_position = (neighbor_segment_particle0_position + neighbor_segment_particle1_position) * 0.5;

			vec3 target_particle0_position = neighbor_segment_center_position + rotate_vec3(neighbor_segment.q, segment_data.particle0_offset[pair_index].xyz);
			vec3 diff0 = target_particle0_position - particles[particle0_handle].x_node_handle.xyz;
			max_strain0 = max(max_strain0, length(diff0) / (segment.torque_rest_length.w + neighbor_segment.torque_rest_length.w) * 2.0);
			vec3 target_particle1_position = neighbor_segment_center_position + rotate_vec3(neighbor_segment.q, segment_data.particle1_offset[pair_index].xyz);
			vec3 diff1 = target_particle1_position - particles[particle1_handle].x_node_handle.xyz;
			max_strain1 = max(max_strain1, length(diff1) / (segment.torque_rest_length.w + neighbor_segment.torque_rest_length.w) * 2.0);
			float t2 = inv_time_step * inv_time_step;
			float stiffness_factor = t2 / segment_pair.stiffness.w;
			float factor = segment.inv_mass / (segment.inv_mass + neighbor_segment.inv_mass + stiffness_factor);

			movement0 += diff0 * factor;
			movement1 += diff1 * factor;

			vec4 q0_correction, q1_correction;
			vec4 rest_darboux_vector = segment_data.rest_darboux_vectors[pair_index];
			project_bend_twist_constraint(inv_time_step,
				segment.q, segment.inv_mass, 
				neighbor_segment.q, neighbor_segment.inv_mass, 
				segment_pair.stiffness.xyz, rest_darboux_vector, q0_correction, q1_correction);

			q_correction += q0_correction;
			sum += 1;
		}
		particles[particle0_handle].acceleration_connectivity_strain.w = max_strain0;
		particles[particle1_handle].acceleration_connectivity_strain.w = max_strain1;

		if(sum != 0){ 
			segment_data_list[segment_index].particle0_position_correction_max_strain.xyz = movement0 / sum;
			segment_data_list[segment_index].particle1_position_correction_max_strain.xyz = movement1 / sum;
			segment_data_list[segment_index].q_correction = q_correction / sum;
		}
		else{
			segment_data_list[segment_index].particle0_position_correction_max_strain.xyz = vec3(0.0, 0.0, 0.0);
			segment_data_list[segment_index].particle1_position_correction_max_strain.xyz = vec3(0.0, 0.0, 0.0);
			segment_data_list[segment_index].q_correction = vec4(0.0, 0.0, 0.0, 0.0);
		}
		
	}
}