#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint segment_pair_size;
	float inv_time_step;
};

void main(){

	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint segment_pair_index = baseID + local_index;

		if(segment_pair_index >= segment_pair_size) break;

		SegmentPair segment_pair = segment_pairs[segment_pair_index];
		if(segment_pair.connectivity_integrity <= 0.f) continue;
		Segment segment0 = segments[segment_pair.segment0_handle];
		Segment segment1 = segments[segment_pair.segment1_handle];
		
		vec3 new_position = (segment0.particle1.x * segment0.inv_mass + segment1.particle0.x * segment1.inv_mass) / (segment0.inv_mass + segment1.inv_mass);
		segments[segment_pair.segment0_handle].particle1.x = new_position;
		segments[segment_pair.segment1_handle].particle0.x = new_position;
	}
}