#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = EXT_TASK_SUBGROUP_COUNT * EXT_TASK_SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((EXT_INVOCATIONS_PER_TASK + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * EXT_INVOCATIONS_PER_TASK;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint connection_size;
	float inv_time_step;
};

void main(){

	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint connection_index = baseID + local_index;

		if(connection_index >= connection_size) break;

		Connection connection = connections[connection_index];
		bool valid = connection.bend_twist_strain_valid.w != 0.0;
		if(!valid) continue;
		Segment segment0 = segments[connection.segment0_handle];
		Segment segment1 = segments[connection.segment1_handle];

		Particle particle0 = particles[connection.segment0_particle_handle];
		Particle particle1 = particles[connection.segment1_particle_handle];

		vec3 new_position = (particle0.x_node_handle.xyz * segment0.inv_mass + particle1.x_node_handle.xyz * segment1.inv_mass) / (segment0.inv_mass + segment1.inv_mass);

		particles[connection.segment0_particle_handle].x_node_handle.xyz = particles[connection.segment1_particle_handle].x_node_handle.xyz = new_position;

	}
}