#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint strand_size;
	float inv_time_step;
	uint frame_index;
};

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

int find_next_segment_pair_handle(in int segment_pair_handle){
	return segment_data_list[segment_pairs[segment_pair_handle].segment1_handle].pair_handles[1];
}

int find_prev_segment_pair_handle(in int segment_pair_handle){
	return segment_data_list[segment_pairs[segment_pair_handle].segment0_handle].pair_handles[0];
}

void main(){

	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint strand_index = baseID + local_index;

		if(strand_index >= strand_size) break;

		Strand strand = strands[strand_index];
		int front_propagate_handle = frame_index % 2 == 0 ? strand.front_propagate_begin_segment_pair_handle : strand.alternative_front_propagate_begin_segment_pair_handle;
		int back_propagate_handle = frame_index % 2 == 0 ? strand.back_propagate_begin_segment_pair_handle : strand.alternative_back_propagate_begin_segment_pair_handle;
		
		while(front_propagate_handle != -1 || back_propagate_handle != -1){
			if(front_propagate_handle != -1) {
				project_bend_twist_constraint(inv_time_step, front_propagate_handle);
				front_propagate_handle = find_next_segment_pair_handle(front_propagate_handle);
				if(front_propagate_handle != -1) find_next_segment_pair_handle(front_propagate_handle);
			}
			if(back_propagate_handle != -1) {
				project_bend_twist_constraint(inv_time_step, back_propagate_handle);
				back_propagate_handle = find_prev_segment_pair_handle(back_propagate_handle);
				if(back_propagate_handle != -1) find_prev_segment_pair_handle(back_propagate_handle);
			}
		}
	}
}

