#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint strand_size;
	float inv_time_step;
	uint frame_index;
};

#define DYNAMIC_STRANDS_SET 0
#define DYNAMIC_STRANDS_PER_STRAND_DATA_SET 1
#include "DynamicStrandsPhysics.glsl"
#include "DynamicStrandsPerStrandData.glsl"


void main(){

	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint strand_index = baseID + local_index;

		if(strand_index >= strand_size) break;

		PerStrandData strand_data = per_strand_data_list[strand_index];
		int front_propagate_handle = strand_data.front_propagate_begin_connection_handle;
		while(front_propagate_handle != -1){
			if(front_propagate_handle != -1) {
				project_bend_twist_constraint(inv_time_step, front_propagate_handle);
				front_propagate_handle = connections[front_propagate_handle].next_handle;
			}
		}
	}
}

