message("======Checking Plugins=======")
set(EvoEngine_Plugins "")

set(EVOENGINE_PLUGINS_INCLUDES "")
set(EVOENGINE_PLUGINS_PCHS "")
set(EVOENGINE_PLUGINS_DEFS "")
set(EVOENGINE_PLUGINS_DLLS "")
set(EVOENGINE_PLUGINS_RESOURCES "")


function(register_evoengine_plugin plugin_name default_enable)
  set(option_name EVOENGINE_ENABLE_${plugin_name}_PLUGIN)
  option(${option_name} "Enable ${plugin_name} plugin." ${default_enable}) 
  if(option_name AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${plugin_name})
	add_subdirectory(${plugin_name})
	if(TARGET ${plugin_name}Plugin)
		if (CMAKE_CXX_COMPILER_ID STREQUAL GNU)
			message(STATUS "Setting G++ flags")
			# G++
			target_compile_options(${plugin_name}Plugin PRIVATE -Werror)
		elseif (CMAKE_CXX_COMPILER_ID STREQUAL MSVC)
			message(STATUS "Setting MSVC flags")
			# MSVC
			target_compile_options(${plugin_name}Plugin PRIVATE /EHsc /W2 /c)
		elseif (CMAKE_CXX_COMPILER_ID STREQUAL Clang)
			message(STATUS "Setting Clang flags")
			# Activate all clang warnings except those that don't really affect much
			target_compile_options(${plugin_name}Plugin PRIVATE -fPIC --no-warnings -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-newline-eof -Wno-padded -Wno-exit-time-destructors -Wno-global-constructors -Wno-constant-conversion)
		endif ()
		message("Enabled [${plugin_name}] plugin.")
		set_target_properties(${plugin_name}Plugin PROPERTIES FOLDER "Plugins")
		set(EvoEngine_Plugins ${EvoEngine_Plugins} ${plugin_name}Plugin)
	else()
		message("[${plugin_name}] plugin not loaded.")
	endif()
  endif()

  set(EvoEngine_Plugins ${EvoEngine_Plugins} PARENT_SCOPE)
  set(EVOENGINE_PLUGINS_INCLUDES ${EVOENGINE_PLUGINS_INCLUDES} PARENT_SCOPE)
  set(EVOENGINE_PLUGINS_PCHS ${EVOENGINE_PLUGINS_PCHS} PARENT_SCOPE)
  set(EVOENGINE_PLUGINS_DEFS ${EVOENGINE_PLUGINS_DEFS} PARENT_SCOPE)
  set(EVOENGINE_PLUGINS_DLLS ${EVOENGINE_PLUGINS_DLLS} PARENT_SCOPE)
  set(EVOENGINE_PLUGINS_RESOURCES ${EVOENGINE_PLUGINS_RESOURCES} PARENT_SCOPE)
endfunction()

register_evoengine_plugin(CudaModule ON)
if (WIN32)
	register_evoengine_plugin(MeshRepair ON)
	register_evoengine_plugin(TextureBaking ON)
	register_evoengine_plugin(Gpr ON)
	register_evoengine_plugin(BillboardClouds ON)
endif()

register_evoengine_plugin(EcoSysLab ON)
register_evoengine_plugin(DigitalAgriculture ON)
register_evoengine_plugin(DatasetGeneration ON)

if (WIN32)
	register_evoengine_plugin(LogGrading ON)
	register_evoengine_plugin(LogScanning ON)
endif()

register_evoengine_plugin(Universe ON)

set(EvoEngine_Plugins ${EvoEngine_Plugins} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_INCLUDES ${EVOENGINE_PLUGINS_INCLUDES} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_PCHS ${EVOENGINE_PLUGINS_PCHS} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_DEFS ${EVOENGINE_PLUGINS_DEFS} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_DLLS ${EVOENGINE_PLUGINS_DLLS} PARENT_SCOPE)
set(EVOENGINE_PLUGINS_RESOURCES ${EVOENGINE_PLUGINS_RESOURCES} PARENT_SCOPE)

