#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

layout(local_size_x_id = 0) in; // Set value for local_size_x via specialization constant with id 0

#define BARRIER()        \
	memoryBarrierShared(); \
	barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint segment_size;
};

void main() {
	int segment_index = int(gl_GlobalInvocationID.x);
	if (segment_index >= segment_size) return;
	segments[segment_index].shear_stretch_strain.w = intBitsToFloat(segment_index);
}