#extension GL_EXT_nonuniform_qualifier : enable

#define EE_RENDER_INFO_BLOCK_SET 0
#define EE_RENDER_INFO_BLOCK_BINDING 0
#include "RenderInfo.slangh"
#define EE_ENVIRONMENT_BLOCK_SET 0
#define EE_ENVIRONMENT_BLOCK_BINDING 1
#include "Environment.slangh"
#define EE_CAMERAS_BLOCK_SET 0
#define EE_CAMERAS_BLOCK_BINDING 2
#include "Cameras.slangh"

#define EE_INSTANCES_BLOCK_SET 0
#define EE_INSTANCES_BLOCK_BINDING 4
#include "Instances.slangh"

#define EE_KERNEL_BLOCK_SET 0
#define EE_KERNEL_BLOCK_BINDING 5
#include "Kernel.slangh"

#define EE_LIGHTING_BLOCK_SET 0
#define EE_DIRECTIONAL_LIGHT_BLOCK_BINDING 6
#define EE_POINT_LIGHT_BLOCK_BINDING 7
#define EE_SPOT_LIGHT_BLOCK_BINDING 8
#include "Lights.slangh"

#ifndef EE_SKIP_PER_FRAME_BINDLESS_TEXTURES
#define EE_TEXTURES_BLOCK_SET 0
#define EE_TEXTURE_2DS_BINDING 9
#define EE_CUBEMAPS_BINDING 10
#include "Textures.slangh"
#endif

#define EE_GLTF_MATERIALS_BLOCK_SET 0
#define EE_GLTF_MATERIALS_BLOCK_BINDING 11
#define EE_GLTF_TEXTURE_INFOS_BLOCK_SET 0
#define EE_GLTF_TEXTURE_INFOS_BLOCK_BINDING 12
#include "GltfMaterial.slangh"
