
#ifndef EE_RAY_QUERY_SHADER
#extension GL_EXT_ray_tracing : enable
#endif

#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_ARB_shading_language_include : enable

#include "PerFrame.slangh"

#include "Vertex.slangh"
layout(std430, set = 1, binding = 0) readonly buffer EE_VERTICES_BLOCK {
  Vertex EE_VERTICES[];
};

layout(std430, set = 1, binding = 1) readonly buffer EE_INDICES_BLOCK {
  uint EE_INDICES[];
};

layout(set = 1, binding = 2) uniform accelerationStructureEXT EE_TLAS;

struct EmissiveTriangleInfo {
  uint instance_index;
  uint primitive_id;
  float cdf;
  float area_pdf;
};

layout(std430, set = 1, binding = 3) readonly buffer EE_EMISSIVE_TRIANGLES_BLOCK {
  EmissiveTriangleInfo EE_EMISSIVE_TRIANGLES[];
};
