#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_ray_tracing : require

#ifndef EE_SHADER_EXECUTION_REORDERING_SUPPORTED
#define EE_SHADER_EXECUTION_REORDERING_SUPPORTED 0
#endif
#if EE_SHADER_EXECUTION_REORDERING_SUPPORTED
#extension GL_NV_shader_invocation_reorder : require
#endif

#include "RayTracingBasic.glsl"
#include "Random.glsl"
#include "GltfRasterMaterial.glsl"
#include "GltfRayTracingBsdf.glsl"
#include "CameraRayTracingPayload.glsl"

layout(set = 2, binding = 0, rgba32f) uniform image2D result_image;
layout(set = 2, binding = 1, r32f) uniform image2D ray_hit_distance_image;
layout(set = 2, binding = 2, rgba32f) uniform image2D radiance_history_image;
layout(set = 2, binding = 3, rgba32f) uniform image2D convergence_history_image;

layout(push_constant) uniform EE_CAMERA_CONSTANTS {
  uint EE_CAMERA_INDEX;
  uint EE_FRAME_ID;
  uint EE_TOTAL_SAMPLES;
  uint EE_FRAME_SAMPLE_SIZE;
  uint EE_SHADER_EXECUTION_REORDERING;
};

layout(location = 0) rayPayloadEXT CameraRayTracingPayload hit_value;

#define EE_CAMERA_RAY_TRACING_TRAVERSAL
#include "CameraRayIntegrator.glsl"

void main() {
  EE_CAMERA_RENDER_PIXEL(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy);
}
