#extension GL_ARB_shading_language_include : enable
#include "RayTracingBasic.glsl"
#include "Random.glsl"

#include "PointCloudRayTracingPayload.glsl"

struct PointCloudSample {
	// Input
	vec3 direction; /**< Ray or sampling direction vector. */
	float padding0;
	vec3 start;     /**< Starting point of the ray or sample. */

	// Output
	uint hit_count;    /**< Flag indicating whether a hit occurred. */
	uint64_t handle; /**< Handle or identifier for the point-cloud object. */
	uint64_t padding1;

	HitInfo hit_info; /**< Detailed information about the hit, if one occurred. */
};

layout(set = 2, binding = 0) buffer EE_POINT_CLOUD_SAMPLE_BLOCK {
  PointCloudSample EE_POINT_CLOUD_SAMPLES[];
};


layout(push_constant) uniform EE_POINT_CLOUD_CONSTANTS {
  uint bounce;
  uint envIndex;
  uint skybox_tex_index;
  uint use_clear_color;
  vec4 clear_color;
};

layout(location = 0) rayPayloadEXT PointCloudRayTracingPayload hit_value;
#define FLT_MAX 3.402823466e+38

void main() 
{
	uint sample_index = gl_LaunchIDEXT.x;
	hit_value.seed = 1664525u * sample_index;
	hit_value.seed = uint(1664525u * EE_RANDOM(hit_value.seed));
	PointCloudSample point_cloud_sample = EE_POINT_CLOUD_SAMPLES[sample_index];
	
	traceRayEXT(EE_TLAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, point_cloud_sample.start, 0, point_cloud_sample.direction, 1e20f, 0);
	point_cloud_sample.hit_count = hit_value.hit_count;
	point_cloud_sample.handle = hit_value.handle;
	point_cloud_sample.hit_info = hit_value.hit_info;
	EE_POINT_CLOUD_SAMPLES[sample_index] = point_cloud_sample;

}