#!/usr/bin/env python3
"""Run the Scots pine synthetic preview workflow.

The default path renders the current ScotsPineDataGenerator scene: its existing
three-pine triangle instantiation, its own main camera, and a quick composite
over the extracted side-view background plate.
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import math
import struct
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Iterable, Sequence


SCENE_MAIN_CAMERA_RESOLUTION = (1943, 1221)
DEFAULT_PREVIEW_RESOLUTION = (1372, 1040)


def _import_pillow():
    try:
        from PIL import Image
    except Exception as exc:
        raise SystemExit("Pillow is required for background compositing.") from exc
    return Image


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_worker(root: Path) -> Path:
    candidates = [
        root / "out" / "install" / "vs2026-x64" / "bin" / "ScotsPineDataGeneratorApp.exe",
        root / "out" / "build" / "vs2026-x64" / "EvoEngine_App" / "RelWithDebInfo" / "ScotsPineDataGeneratorApp.exe",
        root / "out" / "build" / "vs2026-x64" / "EvoEngine_App" / "Debug" / "ScotsPineDataGeneratorApp.exe",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise SystemExit("ScotsPineDataGeneratorApp.exe was not found. Build the app first or pass --worker.")


def write_config(path: Path, values: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by Scripts/scots_pine_synth_preview.py"]
    lines.extend(f"{key}={value}" for key, value in values.items())
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def resolve_project_asset_path(project_path: Path, asset_path: str | Path) -> Path:
    path = Path(asset_path)
    if path.is_absolute():
        return path
    return project_path.resolve().parent / "Assets" / path


def parse_scene_camera_settings(
    scene_path: Path,
) -> tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float], float]:
    text = scene_path.read_text(encoding="utf-8")
    handle = None
    for index, line in enumerate(text.splitlines()):
        if line.strip() == "main_camera:":
            for follow in text.splitlines()[index + 1 : index + 5]:
                stripped = follow.strip()
                if stripped.startswith("entity_handle_:"):
                    handle = stripped.split(":", 1)[1].strip()
                    break
            break
    if not handle:
        raise SystemExit(f"Scene has no main camera handle: {scene_path}")

    fov_deg = 45.0
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if line.strip() == f"h: {handle}":
            for follow in lines[index : index + 80]:
                stripped = follow.strip()
                if stripped.startswith("fov:"):
                    fov_deg = float(stripped.split(":", 1)[1].strip())
                    break
            break

    for index, line in enumerate(lines):
        if line.strip() != f"- h: {handle}":
            continue
        blob = None
        for follow in lines[index + 1 :]:
            stripped = follow.strip()
            if stripped.startswith("- h: "):
                break
            if stripped.startswith('- d: !!binary "'):
                blob = stripped.split('"', 2)[1]
                break
        if not blob:
            break
        values = struct.unpack("<16f", base64.b64decode(blob))
        up = (values[4], values[5], values[6])
        forward = (-values[8], -values[9], -values[10])
        return (
            (values[12], values[13], values[14]),
            normalized(forward, (0.0, 0.0, -1.0)),
            normalized(up, (0.0, 1.0, 0.0)),
            fov_deg,
        )
    raise SystemExit(f"Scene main camera transform was not found: {scene_path}")


def normalized(value: tuple[float, float, float], fallback: tuple[float, float, float]) -> tuple[float, float, float]:
    length = math.sqrt(sum(component * component for component in value))
    if length <= 1.0e-8:
        return fallback
    return tuple(component / length for component in value)


def rotate_y(value: tuple[float, float, float], angle: float) -> tuple[float, float, float]:
    c = math.cos(angle)
    s = math.sin(angle)
    return (c * value[0] + s * value[2], value[1], -s * value[0] + c * value[2])


def write_orbit_camera_rig(
    path: Path,
    scene_path: Path,
    width: int,
    height: int,
    view_count: int,
    radius_override: float | None,
    camera_y_override: float | None,
    start_deg: float,
) -> None:
    camera_position, camera_forward, camera_up, fov_deg = parse_scene_camera_settings(scene_path)
    base_radius = math.sqrt(camera_position[0] * camera_position[0] + camera_position[2] * camera_position[2])
    radius = radius_override if radius_override is not None else base_radius
    camera_y = camera_y_override if camera_y_override is not None else camera_position[1]
    if radius <= 1.0e-6:
        raise SystemExit("--orbit-radius must be positive when the scene camera is at the rotation origin.")

    base_position = (
        (radius, camera_y, 0.0)
        if base_radius <= 1.0e-6
        else (camera_position[0] * radius / base_radius, camera_y, camera_position[2] * radius / base_radius)
    )
    start_angle = math.radians(start_deg)
    fy = (0.5 * height) / math.tan(math.radians(fov_deg * 0.25))
    fx = fy
    cx = 0.5 * width
    cy = 0.5 * height
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    for index in range(view_count):
        angle = start_angle + math.tau * (index / view_count)
        position = rotate_y(base_position, angle)
        forward = normalized(rotate_y(camera_forward, angle), (0.0, 0.0, -1.0))
        up = normalized(rotate_y(camera_up, angle), (0.0, 1.0, 0.0))
        lines.append(
            " ".join(
                [
                    f"orbit_{index:03d}",
                    f"{position[0]:.9f}",
                    f"{position[1]:.9f}",
                    f"{position[2]:.9f}",
                    f"{fx:.9f}",
                    f"{fy:.9f}",
                    f"{cx:.9f}",
                    f"{cy:.9f}",
                    str(width),
                    str(height),
                    "0.01",
                    "50",
                    f"{fov_deg:.9f}",
                    f"{forward[0]:.9f}",
                    f"{forward[1]:.9f}",
                    f"{forward[2]:.9f}",
                    f"{up[0]:.9f}",
                    f"{up[1]:.9f}",
                    f"{up[2]:.9f}",
                ]
            )
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def riff_chunk(tag: bytes, data: bytes) -> bytes:
    return tag + struct.pack("<I", len(data)) + data + (b"\0" if len(data) % 2 else b"")


def riff_list(tag: bytes, data: bytes) -> bytes:
    return b"LIST" + struct.pack("<I", len(data) + 4) + tag + data + (b"\0" if len(data) % 2 else b"")


def write_mjpeg_avi(output_path: Path, frame_paths: Sequence[Path], fps: int, quality: int = 90) -> None:
    Image = _import_pillow()
    if not frame_paths:
        raise SystemExit(f"No frames for video: {output_path}")
    frames: list[bytes] = []
    width = height = 0
    max_frame_size = 0
    for frame_path in frame_paths:
        with Image.open(frame_path) as image:
            rgb = image.convert("RGB")
            if width == 0:
                width, height = rgb.size
            elif rgb.size != (width, height):
                raise SystemExit(f"Video frame size mismatch: {frame_path}")
            buffer = io.BytesIO()
            rgb.save(buffer, format="JPEG", quality=quality)
            data = buffer.getvalue()
            frames.append(data)
            max_frame_size = max(max_frame_size, len(data))

    frame_count = len(frames)
    avih = struct.pack(
        "<IIIIIIIIIIIIII",
        int(1_000_000 / fps),
        max_frame_size * fps,
        0,
        0x10,
        frame_count,
        0,
        1,
        max_frame_size,
        width,
        height,
        0,
        0,
        0,
        0,
    )
    strh = struct.pack(
        "<4s4sIHHIIIIIIIIhhhh",
        b"vids",
        b"MJPG",
        0,
        0,
        0,
        0,
        1,
        fps,
        0,
        frame_count,
        max_frame_size,
        0xFFFFFFFF,
        0,
        0,
        0,
        width,
        height,
    )
    strf = struct.pack("<IiiHH4sIiiII", 40, width, height, 1, 24, b"MJPG", max_frame_size, 0, 0, 0, 0)
    hdrl = riff_list(b"hdrl", riff_chunk(b"avih", avih) + riff_list(b"strl", riff_chunk(b"strh", strh) + riff_chunk(b"strf", strf)))

    movi_payload = bytearray()
    index_entries = []
    for frame in frames:
        offset = len(movi_payload) + 4
        movi_payload.extend(riff_chunk(b"00dc", frame))
        index_entries.append((offset, len(frame)))
    movi = riff_list(b"movi", bytes(movi_payload))
    idx1 = riff_chunk(
        b"idx1",
        b"".join(struct.pack("<4sIII", b"00dc", 0x10, offset, size) for offset, size in index_entries),
    )
    body = hdrl + movi + idx1
    output_path.write_bytes(b"RIFF" + struct.pack("<I", len(body) + 4) + b"AVI " + body)


def vec_sub(a: Sequence[float], b: Sequence[float]) -> tuple[float, float, float]:
    return (float(a[0]) - float(b[0]), float(a[1]) - float(b[1]), float(a[2]) - float(b[2]))


def vec_dot(a: Sequence[float], b: Sequence[float]) -> float:
    return float(a[0]) * float(b[0]) + float(a[1]) * float(b[1]) + float(a[2]) * float(b[2])


def vec_cross(a: Sequence[float], b: Sequence[float]) -> tuple[float, float, float]:
    return (
        float(a[1]) * float(b[2]) - float(a[2]) * float(b[1]),
        float(a[2]) * float(b[0]) - float(a[0]) * float(b[2]),
        float(a[0]) * float(b[1]) - float(a[1]) * float(b[0]),
    )


def project_world_point_to_pixel(point: Sequence[float], view: dict[str, object]) -> dict[str, object]:
    position = view.get("position", [0.0, 0.0, 0.0])
    forward = normalized(tuple(view.get("forward", [0.0, 0.0, -1.0])), (0.0, 0.0, -1.0))
    up = normalized(tuple(view.get("up", [0.0, 1.0, 0.0])), (0.0, 1.0, 0.0))
    right = normalized(vec_cross(forward, up), (1.0, 0.0, 0.0))
    true_up = normalized(vec_cross(right, forward), up)
    intrinsic = view.get("intrinsic", {})
    fx = float(intrinsic.get("fx", 0.0)) if isinstance(intrinsic, dict) else 0.0
    fy = float(intrinsic.get("fy", 0.0)) if isinstance(intrinsic, dict) else 0.0
    cx = float(intrinsic.get("cx", 0.0)) if isinstance(intrinsic, dict) else 0.0
    cy = float(intrinsic.get("cy", 0.0)) if isinstance(intrinsic, dict) else 0.0
    resolution = view.get("resolution", [0, 0])
    width = int(resolution[0])
    height = int(resolution[1])
    near = float(view.get("near", 0.0) or 0.0)
    far = float(view.get("far", 0.0) or 0.0)
    d = vec_sub(point, position)
    z = vec_dot(d, forward)
    in_front = math.isfinite(z) and z > 1.0e-6
    if not in_front:
        return {"x": None, "y": None, "visible": False, "in_front": False, "in_frame": False, "depth": z}
    x = int(round(cx + fx * vec_dot(d, right) / z))
    y = int(round(cy - fy * vec_dot(d, true_up) / z))
    in_depth = (near <= 0.0 or z >= near) and (far <= near or z <= far)
    in_frame = 0 <= x < width and 0 <= y < height
    return {"x": x, "y": y, "visible": bool(in_depth and in_frame), "in_front": True, "in_frame": bool(in_frame), "depth": z}


def screen_space_output_path(rgb_path: Path) -> Path:
    stem = rgb_path.stem
    if stem.endswith("_composited"):
        stem = stem[: -len("_composited")]
    return rgb_path.with_name(stem + "_annotation_screen_space.json")


def organ_screen_record(record: dict[str, object], view: dict[str, object]) -> dict[str, object]:
    out = {key: value for key, value in record.items() if key != "points_world"}
    points = record.get("points_world", [])
    out["points_pixel"] = [
        project_world_point_to_pixel(point, view)
        for point in points
        if isinstance(point, list) and len(point) >= 3
    ]
    return out


def write_screen_space_annotation_json(
    path: Path,
    world_annotation: dict[str, object],
    world_annotation_path: Path,
    profile_point: dict[str, object],
    view: dict[str, object],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    trees = []
    for tree in world_annotation.get("trees", []):
        if not isinstance(tree, dict):
            continue
        organs = tree.get("organs", {})
        if not isinstance(organs, dict):
            organs = {}
        trees.append(
            {
                "tree_index": tree.get("tree_index", len(trees)),
                "organs": {
                    "needles": [organ_screen_record(item, view) for item in organs.get("needles", []) if isinstance(item, dict)],
                    "sheaths": [organ_screen_record(item, view) for item in organs.get("sheaths", []) if isinstance(item, dict)],
                    "stems": [organ_screen_record(item, view) for item in organs.get("stems", []) if isinstance(item, dict)],
                },
            }
        )
    payload = {
        "schema": "scots_pine_annotation_screen_space",
        "version": 1,
        "world_annotation_path": str(world_annotation_path),
        "sample_name": world_annotation.get("sample_name", ""),
        "global_sample_index": profile_point.get("global_sample_index", world_annotation.get("global_sample_index", 0)),
        "local_sample_index": profile_point.get("local_sample_index", world_annotation.get("local_sample_index", 0)),
        "frame_index": profile_point.get("frame_index", world_annotation.get("frame_index", 0)),
        "view_index": profile_point.get("view_index", view.get("index", 0)),
        "view_label": profile_point.get("view_label", view.get("label", "")),
        "resolution": view.get("resolution", [profile_point.get("width", 0), profile_point.get("height", 0)]),
        "camera": {
            "position": view.get("position", []),
            "forward": view.get("forward", []),
            "up": view.get("up", []),
            "intrinsic": view.get("intrinsic", {}),
            "near": view.get("near", 0.0),
            "far": view.get("far", 0.0),
            "fov_deg": view.get("fov_deg", 0.0),
        },
        "sample_counts": world_annotation.get("sample_counts", {}),
        "trees": trees,
    }
    path.write_text(json.dumps(payload, separators=(",", ":")), encoding="utf-8")


def write_screen_space_annotations(run_root: Path, prune_camera_views: bool) -> dict[str, object]:
    start = time.perf_counter()
    engine_profile = load_json(run_root / "render_profile.json")
    datapoints = engine_profile.get("datapoints", []) if isinstance(engine_profile, dict) else []
    if not isinstance(datapoints, list):
        raise SystemExit("Screen-space annotation export requested, but render_profile.json has no datapoints.")
    scene_cache: dict[Path, tuple[dict[str, object], dict[int, dict[str, object]], Path]] = {}
    files_written = 0
    for point in datapoints:
        if not isinstance(point, dict) or not point.get("success"):
            continue
        rgb_path = Path(str(point.get("rgb_path", "")))
        scene_dir = rgb_path.parent
        frame_index = int(point.get("frame_index", 0))
        if scene_dir not in scene_cache:
            world_paths = sorted(scene_dir.glob("*_annotation_skeleton.json"))
            view_paths = sorted(scene_dir.glob("*_camera_views.json"))
            if not world_paths or not view_paths:
                raise SystemExit(f"Missing annotation or camera metadata in {scene_dir}")
            world_annotation = load_json(world_paths[0])
            views = load_json(view_paths[0]).get("views", [])
            if not isinstance(views, list):
                raise SystemExit(f"Camera metadata has no views: {view_paths[0]}")
            scene_cache[scene_dir] = (
                world_annotation,
                {int(view.get("index", i)): view for i, view in enumerate(views) if isinstance(view, dict)},
                view_paths[0],
            )
        world_annotation, views_by_index, camera_views_path = scene_cache[scene_dir]
        view_index = int(point.get("view_index", 0))
        view = views_by_index.get(view_index)
        if view is None:
            raise SystemExit(f"Camera metadata missing view {view_index} in {camera_views_path}")
        output_path = screen_space_output_path(rgb_path)
        write_screen_space_annotation_json(output_path, world_annotation, sorted(scene_dir.glob("*_annotation_skeleton.json"))[frame_index], point, view)
        files_written += 1
    pruned = 0
    if prune_camera_views:
        for _, _, camera_views_path in scene_cache.values():
            if camera_views_path.exists():
                camera_views_path.unlink()
                pruned += 1
        for pattern in ("*_camera_views.json", "*_orbit_camera_rig.txt"):
            for path in run_root.glob(pattern):
                path.unlink(missing_ok=True)
                pruned += 1
    elapsed_ms = (time.perf_counter() - start) * 1000.0
    return {
        "screen_space_annotation_ms": elapsed_ms,
        "screen_space_annotation_files": files_written,
        "screen_space_annotation_ms_per_file": elapsed_ms / files_written if files_written else 0.0,
        "camera_view_files_pruned": pruned,
    }


def build_phase_profile_summary(run_root: Path, worker_wall_ms: float, postprocess: dict[str, object]) -> dict[str, object]:
    engine_profile = load_json(run_root / "render_profile.json")
    datapoints = engine_profile.get("datapoints", []) if isinstance(engine_profile, dict) else []
    phase_totals: dict[str, float] = {}
    success_count = 0
    if isinstance(datapoints, list):
        for point in datapoints:
            if not isinstance(point, dict) or not point.get("success"):
                continue
            success_count += 1
            phases = point.get("phases_ms", {})
            if isinstance(phases, dict):
                for key, value in phases.items():
                    phase_totals[key] = phase_totals.get(key, 0.0) + float(value or 0.0)
    post_ms = float(postprocess.get("screen_space_annotation_ms", 0.0) or 0.0)
    phase_totals["screen_space_annotation"] = post_ms
    phase_totals["engine_worker_wall_observed"] = worker_wall_ms
    phase_totals["pipeline_wall_observed"] = worker_wall_ms + post_ms
    rows = [
        {
            "phase": phase,
            "total_ms": total,
            "mean_ms_per_datapoint": total / success_count if success_count else 0.0,
        }
        for phase, total in sorted(phase_totals.items())
    ]
    summary = {
        "run_root": str(run_root),
        "datapoints": success_count,
        "worker_wall_ms": worker_wall_ms,
        "note": "Engine phase rows are diagnostic and may be nested; do not sum them as exclusive wall-clock steps.",
        "postprocess": postprocess,
        "phases": rows,
    }
    (run_root / "phase_profile_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    csv_lines = ["phase,total_ms,mean_ms_per_datapoint\n"]
    for row in rows:
        csv_lines.append(f"{row['phase']},{row['total_ms']:.4f},{row['mean_ms_per_datapoint']:.4f}\n")
    (run_root / "phase_profile_summary.csv").write_text("".join(csv_lines), encoding="utf-8")
    return summary


def run_synthetic_worker(worker: Path, config_path: Path) -> tuple[int, float, str]:
    command = [str(worker), "--synthetic-config", str(config_path)]
    print("[scots-pine-preview] cmd:", " ".join(command), flush=True)
    worker_start = time.perf_counter()
    worker_output_lines: list[str] = []
    process = subprocess.Popen(
        command,
        cwd=str(worker.parent),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        bufsize=1,
    )
    assert process.stdout is not None
    for line in process.stdout:
        print(line, end="", flush=True)
        worker_output_lines.append(line)
    return process.wait(), (time.perf_counter() - worker_start) * 1000.0, "".join(worker_output_lines)


def merge_render_profiles(run_root: Path, profile_parts: Sequence[Path]) -> None:
    if not profile_parts:
        return
    combined = load_json(profile_parts[0])
    datapoints: list[dict[str, object]] = []
    for part in profile_parts:
        profile = load_json(part)
        part_points = profile.get("datapoints", []) if isinstance(profile, dict) else []
        if isinstance(part_points, list):
            datapoints.extend(point for point in part_points if isinstance(point, dict))
    for index, point in enumerate(datapoints):
        point["datapoint_index"] = index
    combined["datapoints"] = datapoints
    successful = sum(1 for point in datapoints if point.get("success"))
    failed = len(datapoints) - successful
    if isinstance(combined.get("summary"), dict):
        combined["summary"]["datapoints"] = len(datapoints)
        combined["summary"]["successful_datapoints"] = successful
        combined["summary"]["failed_datapoints"] = failed
    if isinstance(combined.get("run"), dict):
        global_indices = [int(point.get("global_sample_index", 0)) for point in datapoints]
        combined["run"]["sample_count"] = len(set(global_indices))
        combined["run"]["start_index"] = min(global_indices) if global_indices else 0
    (run_root / "render_profile.json").write_text(json.dumps(combined, indent=2), encoding="utf-8")

    csv_parts = [part.with_suffix(".csv") for part in profile_parts]
    lines: list[str] = []
    for part in csv_parts:
        if not part.exists():
            continue
        part_lines = part.read_text(encoding="utf-8").splitlines()
        if not part_lines:
            continue
        if not lines:
            lines.append(part_lines[0])
        lines.extend(part_lines[1:])
    if lines:
        (run_root / "render_profile.csv").write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_config_overrides(overrides: Sequence[str]) -> dict[str, str]:
    parsed: dict[str, str] = {}
    for override in overrides:
        if "=" not in override:
            raise SystemExit(f"Invalid --config-override value, expected key=value: {override}")
        key, value = override.split("=", 1)
        key = key.strip()
        if not key:
            raise SystemExit(f"Invalid --config-override value, empty key: {override}")
        parsed[key] = value.strip()
    return parsed


def mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def stddev(values: list[float], avg: float) -> float:
    if len(values) < 2:
        return 0.0
    return math.sqrt(sum((value - avg) ** 2 for value in values) / len(values))


def load_json(path: Path) -> dict[str, object]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def build_preview_profile(summary: list[dict[str, object]], run_root: Path) -> dict[str, object]:
    datapoint_totals: list[float] = []
    rows: list[dict[str, object]] = []
    for item in summary:
        scene_dir = Path(str(item.get("scene_dir", run_root)))
        engine_profile_path = Path(str(item.get("engine_profile", scene_dir / "render_profile.json")))
        engine_profile = load_json(engine_profile_path)
        datapoints = engine_profile.get("datapoints", []) if isinstance(engine_profile, dict) else []
        worker_wall_ms = float(item.get("worker_wall_ms", 0.0) or 0.0)
        datapoint_count = max(1, len(datapoints) if isinstance(datapoints, list) else 0)
        worker_wall_per_datapoint = worker_wall_ms / datapoint_count
        postprocess_per_datapoint = float(item.get("postprocess_ms", 0.0) or 0.0) / datapoint_count
        if not isinstance(datapoints, list):
            continue
        for point in datapoints:
            if not isinstance(point, dict):
                continue
            phases = point.get("phases_ms", {})
            engine_total = float(phases.get("total_engine", 0.0) if isinstance(phases, dict) else 0.0)
            total_ms = worker_wall_per_datapoint
            warmup = bool(point.get("warmup", False))
            success = bool(point.get("success", False))
            row = {
                "scene": item.get("scene", item.get("batch", "")),
                "datapoint_index": point.get("datapoint_index", 0),
                "global_sample_index": point.get("global_sample_index", 0),
                "frame_index": point.get("frame_index", 0),
                "view_index": point.get("view_index", 0),
                "warmup": warmup,
                "success": success,
                "engine_total_ms": engine_total,
                "postprocess_ms": postprocess_per_datapoint,
                "worker_wall_ms": worker_wall_per_datapoint,
                "total_profiled_ms": total_ms,
                "engine_profile": str(engine_profile_path),
            }
            rows.append(row)
            if success and not warmup:
                datapoint_totals.append(total_ms)

    avg = mean(datapoint_totals)
    samples_per_hour = 3_600_000.0 / avg if avg > 0.0 else 0.0
    return {
        "run_root": str(run_root),
        "summary": {
            "estimated_datapoints": len(datapoint_totals),
            "mean_total_ms": avg,
            "min_total_ms": min(datapoint_totals) if datapoint_totals else 0.0,
            "max_total_ms": max(datapoint_totals) if datapoint_totals else 0.0,
            "stddev_total_ms": stddev(datapoint_totals, avg),
            "samples_per_hour": samples_per_hour,
        },
        "datapoints": rows,
    }


def write_preview_profile_csv(path: Path, profile: dict[str, object]) -> None:
    datapoints = profile.get("datapoints", [])
    lines = [
        "scene,datapoint_index,global_sample_index,frame_index,view_index,warmup,success,engine_total_ms,postprocess_ms,"
        "worker_wall_ms,total_profiled_ms,engine_profile\n"
    ]
    if isinstance(datapoints, list):
        for point in datapoints:
            if not isinstance(point, dict):
                continue
            lines.append(
                f"{point.get('scene', '')},{point.get('datapoint_index', 0)},{point.get('global_sample_index', 0)},"
                f"{point.get('frame_index', 0)},{point.get('view_index', 0)},{int(bool(point.get('warmup', False)))},"
                f"{int(bool(point.get('success', False)))},{float(point.get('engine_total_ms', 0.0)):.4f},"
                f"{float(point.get('postprocess_ms', 0.0)):.4f},"
                f"{float(point.get('worker_wall_ms', 0.0)):.4f},"
                f"{float(point.get('total_profiled_ms', 0.0)):.4f},{point.get('engine_profile', '')}\n"
            )
    path.write_text("".join(lines), encoding="utf-8")


def parse_resolution(text: str) -> tuple[int, int]:
    normalized = text.strip().lower()
    if normalized == "scene":
        return SCENE_MAIN_CAMERA_RESOLUTION
    if normalized == "preview":
        return DEFAULT_PREVIEW_RESOLUTION
    if "x" not in normalized:
        raise argparse.ArgumentTypeError("Resolution must be WxH, 'scene', or 'background'.")
    w_text, h_text = normalized.split("x", 1)
    width = int(w_text)
    height = int(h_text)
    if width <= 0 or height <= 0:
        raise argparse.ArgumentTypeError("Resolution must be positive.")
    return width, height


def iter_existing_required(scene_dir: Path) -> Iterable[Path]:
    patterns = [
        "*_rgba.png",
        "*_composited.jpg",
        "*_depth.png",
        "*_instance_mask.png",
        "*_foreground_mask.png",
        "*_composited.png",
        "*_tree0_flow.yaml",
        "*_tree1_flow.yaml",
        "*_tree2_flow.yaml",
        "*_tree0_node.yaml",
        "*_tree1_node.yaml",
        "*_tree2_node.yaml",
        "*_tree0_needle_skeleton.yaml",
        "*_tree1_needle_skeleton.yaml",
        "*_tree2_needle_skeleton.yaml",
        "*_annotation_skeleton.json",
        "*_annotation_screen_space.json",
        "*_annotation_overlay.png",
        "*_camera_views.json",
        "*_orbit_camera_rig.txt",
        "*.avi",
    ]
    for pattern in patterns:
        yield from scene_dir.rglob(pattern)


def parse_args() -> argparse.Namespace:
    root = repo_root()
    parser = argparse.ArgumentParser(description="Run a Scots pine synthetic render preview.")
    parser.add_argument("--worker", type=Path, default=None)
    parser.add_argument("--scene-count", type=int, default=1)
    parser.add_argument("--frame-count", type=int, default=1)
    parser.add_argument(
        "--render-mode",
        choices=("rasterization", "ray-tracing"),
        default="rasterization",
        help="Ray tracing is available for diagnostics, but rasterization is the supported synthetic data path.",
    )
    parser.add_argument("--base-seed", type=int, default=12345)
    parser.add_argument("--start-index", type=int, default=0)
    parser.add_argument("--worker-id", type=int, default=0)
    parser.add_argument("--worker-count", type=int, default=1)
    parser.add_argument("--engine-sample-chunk-size", type=int, default=0)
    parser.add_argument("--output-name", default="scene")
    parser.add_argument("--out-root", type=Path, default=root / "output" / "scots_pine_synthetic")
    parser.add_argument("--project", type=Path, default=root / "Resources" / "DigitalAgricultureProject" / "test.eveproj")
    parser.add_argument("--scene-path", default="ScotsPineDataGenerator.evescene")
    parser.add_argument(
        "--descriptor-path",
        default="New ScotsPineDescriptor.spine",
        help="Project-assets-relative descriptor path, or an absolute path inside the project's Assets folder.",
    )
    parser.add_argument("--background-image", type=Path, default=root / "Resources" / "ScotsPineSynthetic" / "Backgrounds" / "extracted_side_view.png")
    parser.add_argument("--background-dir", type=Path, default=root / "Resources" / "ScotsPineSynthetic" / "Backgrounds")
    parser.add_argument("--render-resolution", default="preview", help="WxH, 'preview', 'scene', or 'background'.")
    parser.add_argument("--max-target-gdd", type=float, default=4500.0)
    parser.add_argument("--triangle-side-length", type=float, default=3.0)
    parser.add_argument("--triangle-offset-x", type=float, default=0.0)
    parser.add_argument("--triangle-offset-z", type=float, default=0.0)
    parser.add_argument("--triangle-yaw-deg", type=float, default=0.0)
    parser.add_argument("--camera-position-offset-y", type=float, default=0.0)
    parser.add_argument("--camera-screen-offset-x-percent", type=float, default=0.0)
    parser.add_argument("--camera-screen-offset-y-percent", type=float, default=0.0)
    parser.add_argument("--orbit-views", type=int, default=0, help="Render this many orbit views around world Y at the origin.")
    parser.add_argument("--orbit-radius", type=float, default=None, help="Override orbit radius; default uses the scene main camera radius.")
    parser.add_argument("--orbit-camera-y", type=float, default=None, help="Override orbit camera Y; default uses the scene main camera Y.")
    parser.add_argument("--orbit-start-deg", type=float, default=0.0)
    parser.add_argument("--orbit-video", action="store_true", help="Write clean and annotation-overlay orbit videos after rendering.")
    parser.add_argument("--orbit-video-fps", type=int, default=60)
    parser.add_argument("--orbit-video-quality", type=int, default=90)
    parser.add_argument("--visual-scale", type=float, default=20.0)
    parser.add_argument("--ambient-light", type=float, default=0.8)
    parser.add_argument("--directional-light", type=float, default=1.25)
    parser.add_argument("--scene-pine-growth-mode", choices=("direct", "calendar_scene_multiplier"), default="calendar_scene_multiplier")
    parser.add_argument("--scene-gdd-multiplier", type=float, default=None)
    parser.add_argument("--calendar-step-days", type=float, default=1.0)
    parser.add_argument("--calendar-start-from-reset", dest="calendar_start_from_reset", action="store_true", default=True)
    parser.add_argument("--no-calendar-start-from-reset", dest="calendar_start_from_reset", action="store_false")
    parser.add_argument("--ray-trace-samples", type=int, default=4)
    parser.add_argument("--ray-trace-bounces", type=int, default=4)
    parser.add_argument("--profile-warmup-datapoints", type=int, default=1)
    parser.add_argument("--writer-threads", type=int, default=2)
    parser.add_argument("--rgb-output-format", choices=("jpg", "png"), default="jpg")
    parser.add_argument("--jpg-quality", type=int, default=95)
    parser.add_argument("--png-compression-level", type=int, default=1)
    parser.add_argument("--plant-blur-radius-px", type=float, default=0.0)
    parser.add_argument(
        "--non-strict-parity",
        dest="strict_parity",
        action="store_false",
        default=True,
        help="Allow headless-only growth/descriptor overrides. Strict app/headless parity is the default.",
    )
    parser.add_argument("--override-scene-growth", action="store_true")
    parser.add_argument("--preserve-scene-pine-seed", dest="preserve_scene_pine_seed", action="store_true", default=True)
    parser.add_argument("--vary-scene-pine-seed", dest="preserve_scene_pine_seed", action="store_false")
    parser.add_argument("--image-only", action="store_true", help="Export only render images plus postprocessed masks/composites.")
    parser.add_argument("--export-synthetic-labels", action="store_true", help="Export procedural organ/cohort label PNGs.")
    parser.add_argument("--composite-background", dest="composite_background", action="store_true", default=True)
    parser.add_argument("--no-composite-background", dest="composite_background", action="store_false")
    parser.add_argument("--foreground-mask", dest="write_foreground_mask", action="store_true", default=True)
    parser.add_argument("--no-foreground-mask", dest="write_foreground_mask", action="store_false")
    parser.add_argument("--annotation-overlay", dest="export_annotation_overlay", action="store_true", default=True)
    parser.add_argument("--no-annotation-overlay", dest="export_annotation_overlay", action="store_false")
    parser.add_argument("--export-annotation-screen-space", action="store_true")
    parser.add_argument("--prune-camera-views", action="store_true")
    parser.add_argument("--write-raw-rgba", action="store_true", help="Keep debug transparent RGBA PNGs in addition to composited outputs.")
    parser.add_argument(
        "--config-override",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="Append or replace one synthetic render config value after preview defaults.",
    )
    parser.add_argument("--keep-going", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = repo_root()
    background_image = args.background_image.resolve()
    needs_background = args.composite_background or args.render_resolution.strip().lower() == "background"
    if args.render_resolution.strip().lower() == "background" and not background_image.exists():
        raise SystemExit(f"Background image not found for background-sized render: {background_image}")
    if needs_background and not background_image.exists() and not args.background_dir.exists():
        raise SystemExit(f"No compositing background found: {background_image} or {args.background_dir}")

    if args.render_resolution.strip().lower() == "background":
        Image = _import_pillow()
        with Image.open(background_image) as img:
            width, height = img.size
    else:
        width, height = parse_resolution(args.render_resolution)

    if args.ray_trace_samples <= 0:
        raise SystemExit("--ray-trace-samples must be > 0")
    if args.ray_trace_bounces <= 0:
        raise SystemExit("--ray-trace-bounces must be > 0")
    if args.profile_warmup_datapoints < 0:
        raise SystemExit("--profile-warmup-datapoints must be >= 0")
    if args.scene_count <= 0:
        raise SystemExit("--scene-count must be > 0")
    if args.start_index < 0:
        raise SystemExit("--start-index must be >= 0")
    if args.worker_count <= 0:
        raise SystemExit("--worker-count must be > 0")
    if args.worker_id < 0 or args.worker_id >= args.worker_count:
        raise SystemExit("--worker-id must be in [0, worker_count)")
    if args.engine_sample_chunk_size < 0:
        raise SystemExit("--engine-sample-chunk-size must be >= 0")
    if args.writer_threads <= 0:
        raise SystemExit("--writer-threads must be > 0")
    if args.orbit_views < 0:
        raise SystemExit("--orbit-views must be >= 0")
    if args.orbit_views and args.orbit_views < 2:
        raise SystemExit("--orbit-views must be 0 or at least 2")
    if args.orbit_radius is not None and args.orbit_radius <= 0.0:
        raise SystemExit("--orbit-radius must be > 0")
    if args.orbit_video_fps <= 0:
        raise SystemExit("--orbit-video-fps must be > 0")
    if not (1 <= args.orbit_video_quality <= 100):
        raise SystemExit("--orbit-video-quality must be in [1, 100]")
    if args.orbit_video and not args.orbit_views:
        raise SystemExit("--orbit-video requires --orbit-views")
    if not (1 <= args.jpg_quality <= 100):
        raise SystemExit("--jpg-quality must be in [1, 100]")
    if not (0 <= args.png_compression_level <= 9):
        raise SystemExit("--png-compression-level must be in [0, 9]")
    if args.strict_parity:
        if args.orbit_views:
            raise SystemExit("--non-strict-parity is required with --orbit-views")
        if args.override_scene_growth:
            raise SystemExit("--non-strict-parity is required with --override-scene-growth")
        if args.scene_gdd_multiplier is not None:
            raise SystemExit("--non-strict-parity is required with --scene-gdd-multiplier")
        if not args.preserve_scene_pine_seed:
            raise SystemExit("--non-strict-parity is required with --vary-scene-pine-seed")

    worker = args.worker.resolve() if args.worker else default_worker(root)
    run_root = (args.out_root / f"preview_{datetime.now().strftime('%Y%m%d_%H%M%S')}").resolve()
    run_root.mkdir(parents=True, exist_ok=True)
    orbit_camera_rig = None
    if args.orbit_views:
        orbit_camera_rig = run_root / f"{args.output_name}_orbit_camera_rig.txt"
        write_orbit_camera_rig(
            orbit_camera_rig,
            resolve_project_asset_path(args.project, args.scene_path),
            width,
            height,
            args.orbit_views,
            args.orbit_radius,
            args.orbit_camera_y,
            args.orbit_start_deg,
        )
        print(f"[scots-pine-preview] orbit rig: {orbit_camera_rig}")

    summary: list[dict[str, object]] = []

    config_path = run_root / "synthetic_render.cfg"
    config_values = {
        "project_path": args.project.resolve(),
        "scene_path": args.scene_path,
        "descriptor_path": args.descriptor_path,
        "output_root": run_root,
        "output_name": args.output_name,
        "sample_count": args.scene_count,
        "start_index": args.start_index,
        "worker_id": args.worker_id,
        "worker_count": args.worker_count,
        "base_seed": args.base_seed,
        "seed_a": args.base_seed,
        "seed_b": args.base_seed + 1,
        "seed_c": args.base_seed + 2,
        "frame_count": args.frame_count,
        "width": width,
        "height": height,
        "triangle_side_length": args.triangle_side_length,
        "triangle_offset_x": args.triangle_offset_x,
        "triangle_offset_z": args.triangle_offset_z,
        "triangle_yaw_deg": args.triangle_yaw_deg,
        "camera_position_offset_y": args.camera_position_offset_y,
        "camera_screen_offset_x_percent": args.camera_screen_offset_x_percent,
        "camera_screen_offset_y_percent": args.camera_screen_offset_y_percent,
        "visual_scale": args.visual_scale,
        "ambient_light": args.ambient_light,
        "directional_light": args.directional_light,
        "scene_pine_growth_mode": args.scene_pine_growth_mode,
        "strict_parity": 1 if args.strict_parity else 0,
        "render_mode": "ray_tracing" if args.render_mode == "ray-tracing" else args.render_mode,
        "calendar_step_days": args.calendar_step_days,
        "calendar_start_from_reset": 1 if args.calendar_start_from_reset else 0,
        "ray_trace_samples": args.ray_trace_samples,
        "ray_trace_bounces": args.ray_trace_bounces,
        "profile_warmup_datapoints": args.profile_warmup_datapoints,
        "writer_threads": args.writer_threads,
        "rgb_output_format": args.rgb_output_format,
        "jpg_quality": args.jpg_quality,
        "png_compression_level": args.png_compression_level,
        "plant_blur_radius_px": args.plant_blur_radius_px,
        "transparent_bg": 1,
        "batch_output_subdirs": 1,
        "keep_going": 1 if args.keep_going else 0,
        "composite_background": 1 if args.composite_background else 0,
        "write_foreground_mask": 1 if args.write_foreground_mask else 0,
        "write_raw_rgba": 1 if args.write_raw_rgba else 0,
        "load_scene": 1,
        "use_scene_main_camera": 0 if args.orbit_views else 1,
        "use_scene_pine_transforms": 1,
        "use_scene_pine_growth": 0 if args.override_scene_growth else 1,
        "preserve_scene_pine_seed": 1 if args.preserve_scene_pine_seed else 0,
        "export_depth": 0 if args.image_only else 1,
        "export_instance_mask": 0 if args.image_only else 1,
        "export_synthetic_labels": 1 if args.export_synthetic_labels else 0,
        "export_flow_graph": 0 if args.image_only else 1,
        "export_node_graph": 0 if args.image_only else 1,
        "export_needle_skeleton": 0 if args.image_only else 1,
        "export_annotation_skeleton": 1,
        "export_annotation_overlay": 1 if args.export_annotation_overlay else 0,
    }
    if not args.strict_parity:
        config_values["max_target_gdd"] = args.max_target_gdd
    if background_image.exists():
        config_values["background_image"] = background_image
    if args.background_dir.exists():
        config_values["background_dir"] = args.background_dir.resolve()
    if orbit_camera_rig:
        config_values["camera_rig_file"] = orbit_camera_rig
        config_values["camera_position_offset_y"] = 0.0
        config_values["camera_screen_offset_x_percent"] = 0.0
        config_values["camera_screen_offset_y_percent"] = 0.0
    if args.scene_gdd_multiplier is not None:
        config_values["scene_pine_target_gdd_multiplier"] = args.scene_gdd_multiplier
    config_values.update(parse_config_overrides(args.config_override))
    chunk_size = args.engine_sample_chunk_size if args.engine_sample_chunk_size > 0 else args.scene_count
    chunk_size = min(max(1, chunk_size), args.scene_count)
    chunked = chunk_size < args.scene_count
    profile_parts: list[Path] = []
    return_code = 0
    worker_wall_ms = 0.0
    for chunk_offset in range(0, args.scene_count, chunk_size):
        chunk_index = len(profile_parts)
        chunk_count = min(chunk_size, args.scene_count - chunk_offset)
        chunk_config = dict(config_values)
        chunk_config["sample_count"] = chunk_count
        chunk_config["start_index"] = args.start_index + chunk_offset
        chunk_config_path = run_root / ("synthetic_render.cfg" if not chunked else f"synthetic_render_part_{chunk_index:03d}.cfg")
        write_config(chunk_config_path, chunk_config)
        chunk_return_code, chunk_worker_wall_ms, chunk_stdout = run_synthetic_worker(worker, chunk_config_path)
        worker_wall_ms += chunk_worker_wall_ms
        chunk_status = "ok" if chunk_return_code == 0 else "failed"
        part_profile = run_root / "render_profile.json"
        part_csv = run_root / "render_profile.csv"
        if chunked and part_profile.exists():
            renamed_profile = run_root / f"render_profile_part_{chunk_index:03d}.json"
            part_profile.replace(renamed_profile)
            if part_csv.exists():
                part_csv.replace(run_root / f"render_profile_part_{chunk_index:03d}.csv")
            part_profile = renamed_profile
        if part_profile.exists():
            profile_parts.append(part_profile)
        summary.append(
            {
                "batch": args.output_name,
                "status": chunk_status,
                "exit_code": chunk_return_code,
                "scene_dir": str(run_root),
                "config": str(chunk_config_path),
                "engine_profile": str(part_profile),
                "base_seed": args.base_seed,
                "start_index": args.start_index + chunk_offset,
                "sample_count": chunk_count,
                "render_mode": chunk_config["render_mode"],
                "ray_trace_samples": args.ray_trace_samples,
                "ray_trace_bounces": args.ray_trace_bounces,
                "profile_warmup_datapoints": args.profile_warmup_datapoints,
                "worker_wall_ms": chunk_worker_wall_ms,
                "postprocess_ms": 0.0,
                "output_file_count": 0,
                "stdout": chunk_stdout,
            }
        )
        print(f"[scots-pine-preview] {args.output_name} chunk {chunk_index + 1}: {chunk_status}")
        if chunk_return_code != 0:
            return_code = chunk_return_code
            if not args.keep_going:
                break
    if profile_parts:
        merge_render_profiles(run_root, profile_parts)
    if return_code == 0 and any(item["status"] != "ok" for item in summary):
        return_code = 1
    status = "ok" if return_code == 0 else "failed"
    print(f"[scots-pine-preview] {args.output_name}: {status}")

    if args.orbit_video and return_code == 0:
        engine_profile = load_json(run_root / "render_profile.json")
        datapoints = engine_profile.get("datapoints", []) if isinstance(engine_profile, dict) else []
        if not isinstance(datapoints, list):
            raise SystemExit("Orbit video requested, but render_profile.json has no datapoints.")
        ordered = sorted(
            (point for point in datapoints if isinstance(point, dict) and point.get("success")),
            key=lambda point: (
                int(point.get("global_sample_index", 0)),
                int(point.get("frame_index", 0)),
                int(point.get("view_index", 0)),
            ),
        )
        clean_frames = [Path(str(point.get("rgb_path", ""))) for point in ordered]
        overlay_frames = [Path(str(point.get("annotation_overlay_path", ""))) for point in ordered]
        expected_frames = args.scene_count * args.frame_count * args.orbit_views
        if len(clean_frames) != expected_frames:
            raise SystemExit(f"Expected {expected_frames} orbit frames, found {len(clean_frames)}.")
        missing = [path for path in clean_frames + overlay_frames if not path.exists()]
        if missing:
            raise SystemExit(f"Orbit video frame is missing: {missing[0]}")
        clean_video = run_root / f"{args.output_name}_clean_{len(clean_frames)}f_{args.orbit_video_fps}fps.avi"
        overlay_video = run_root / f"{args.output_name}_skeleton_{len(overlay_frames)}f_{args.orbit_video_fps}fps.avi"
        write_mjpeg_avi(clean_video, clean_frames, args.orbit_video_fps, args.orbit_video_quality)
        write_mjpeg_avi(overlay_video, overlay_frames, args.orbit_video_fps, args.orbit_video_quality)
        summary[-1]["orbit_clean_video"] = str(clean_video)
        summary[-1]["orbit_skeleton_video"] = str(overlay_video)
        print(f"[scots-pine-preview] clean video   : {clean_video}")
        print(f"[scots-pine-preview] skeleton video: {overlay_video}")

    postprocess_profile: dict[str, object] = {}
    if args.export_annotation_screen_space and return_code == 0:
        postprocess_profile = write_screen_space_annotations(run_root, args.prune_camera_views)
        for item in summary:
            item.update(postprocess_profile)
            sample_fraction = float(item.get("sample_count", 0) or 0) / float(max(1, args.scene_count))
            item["postprocess_ms"] = float(postprocess_profile["screen_space_annotation_ms"]) * sample_fraction
        print(
            "[scots-pine-preview] screen-space annotation JSONs: "
            f"{postprocess_profile['screen_space_annotation_files']} "
            f"({float(postprocess_profile['screen_space_annotation_ms']):.1f} ms)"
        )

    files = list(iter_existing_required(run_root))
    for item in summary:
        item["output_file_count"] = len(files)
    phase_profile = build_phase_profile_summary(run_root, worker_wall_ms, postprocess_profile)
    summary_path = run_root / "preview_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    preview_profile = build_preview_profile(summary, run_root)
    preview_profile_json = run_root / "preview_profile.json"
    preview_profile_csv = run_root / "preview_profile.csv"
    preview_profile_json.write_text(json.dumps(preview_profile, indent=2), encoding="utf-8")
    write_preview_profile_csv(preview_profile_csv, preview_profile)
    ok_count = sum(1 for item in summary if item["status"] == "ok")
    print(f"[scots-pine-preview] run root: {run_root}")
    print(f"[scots-pine-preview] summary : {summary_path}")
    print(f"[scots-pine-preview] profile : {preview_profile_json}")
    print(f"[scots-pine-preview] phases  : {run_root / 'phase_profile_summary.json'}")
    profile_summary = preview_profile.get("summary", {})
    if isinstance(profile_summary, dict) and profile_summary.get("estimated_datapoints", 0):
        print(f"[scots-pine-preview] samples/hour: {float(profile_summary['samples_per_hour']):.2f}")
    datapoints = preview_profile.get("datapoints", [])
    if isinstance(datapoints, list):
        datapoint_ok_count = sum(1 for point in datapoints if isinstance(point, dict) and point.get("success"))
        print(f"[scots-pine-preview] datapoints ok/total: {datapoint_ok_count}/{len(datapoints)}")
    print(f"[scots-pine-preview] workers ok/total: {ok_count}/{len(summary)}")
    return 0 if ok_count == len(summary) else 1


if __name__ == "__main__":
    raise SystemExit(main())
