#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_EXT_shader_atomic_float2 : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "FloatOrderedInt.glsl"
#include "Math.glsl"

#define INFINITY uintBitsToFloat(0x7F800000)

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 1, binding = 0) buffer MIN_DISTANCE_BLOCK {
  int global_min_distance;
  uint global_index_of_min;
  int padding0;
  int padding1;
};

#define BARRIER()        \
  memoryBarrierShared(); \
  barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
  mat4 projection_view;
  vec2 point;
  vec2 screen_size;

  uint segment_size;
  float point_size;
  float injection_amount;
};

void main() {
  [[unroll]]
  for (uint i = 0; i < ITERATIONS_PER_TASK; i++) {
    uint local_index = laneID + i * WORKGROUP_SIZE;
    uint segment_index = baseID + local_index;

    if (segment_index >= segment_size)
      break;

    Segment segment = segments[segment_index];
    if (segment.screen_depth != INFINITY && global_min_distance == floatToOrderedInt(segment.screen_depth)) {
      // useful for debugging, but not needed
      // global_index_of_min = segment_index;

      segment.fungus_density = segment.fungus_density + injection_amount;
    }
    segments[segment_index] = segment;
  }
}