#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_EXT_shader_atomic_float2 : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "FloatOrderedInt.glsl"
#include "LineCircleIntersect.glsl"
#include "Math.glsl"

#define INFINITY uintBitsToFloat(0x7F800000)

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(std430, set = 1, binding = 0) buffer MIN_DISTANCE_BLOCK {
  int global_min_distance;
  uint global_index_of_min;
  int padding0;
  int padding1;
};

#define BARRIER()        \
  memoryBarrierShared(); \
  barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
  mat4 projection_view;
  vec2 point;
  vec2 screen_size;

  uint segment_size;
  float point_size;
  float injection_amount;
};

void main() {
  float min_distance_to_screen = INFINITY;
  uint index_of_min = 0;

  BARRIER();

  [[unroll]]
  for (uint i = 0; i < ITERATIONS_PER_TASK; i++) {
    uint local_index = laneID + i * WORKGROUP_SIZE;
    uint segment_index = baseID + local_index;

    if (segment_index >= segment_size)
      break;

    segments[segment_index].screen_depth = INFINITY;
    // only allow injection if there is no fungus already.
    // we set threshold to 0.5 * injection amount so small diffusions to surrounding segments will not prohibit
    // injection but the most recently injected segments are avoided.
    if (segments[segment_index].RW >= 0.5 * injection_amount)
      continue;

    Segment segment = segments[segment_index];

    vec3 particle0_position = segment.particle0.x;
    vec3 particle1_position = segment.particle1.x;

    vec4 particle0_screen_space_coord = projection_view * vec4(particle0_position, 1.0f);
    vec3 particle0_screen_space_position = particle0_screen_space_coord.xyz / particle0_screen_space_coord.w;
    vec4 particle1_screen_space_coord = projection_view * vec4(particle1_position, 1.0f);
    vec3 particle1_screen_space_position = particle1_screen_space_coord.xyz / particle1_screen_space_coord.w;

    vec2 particle0_screen =
        vec2((particle0_screen_space_position.x + 1.0f) * 0.5f, (-particle0_screen_space_position.y + 1.0f) * 0.5f) *
        screen_size;
    vec2 particle1_screen =
        vec2((particle1_screen_space_position.x + 1.0f) * 0.5f, (-particle1_screen_space_position.y + 1.0f) * 0.5f) *
        screen_size;

    if (LineCircleIntersect(particle0_screen, particle1_screen, point, point_size)) {
      float distance_to_screen = min(particle1_screen_space_position.z, particle0_screen_space_position.z);
      segments[segment_index].screen_depth = distance_to_screen;

      // find minimum among thread to avoid atomic operations
      if (distance_to_screen < min_distance_to_screen) {
        min_distance_to_screen = distance_to_screen;
        index_of_min = segment_index;
      }
    }
  }

  // now use subgroups to determine the minimum distance among all work groups
  float subgroup_min_distance = subgroupMin(min_distance_to_screen);
  if (subgroupElect()) {
    atomicMin(global_min_distance, floatToOrderedInt(subgroup_min_distance));
  }
}