#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"
#include "Noise.glsl"
const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint leaf_size;
	float ground_height;
	float rotation_correction_strength;
	float air_resistance_strength;
	
	vec3 disturbance_frequency;
	float disturbance_strength;
};


vec3 calculate_torque(in vec4 current_q, in vec4 target_q){
	vec4 relative_q = quat_mul(conjugate(current_q), target_q);
	float angle = 2.f * acos(clamp(relative_q.w, -1.f, 1.f));
	vec3 axis = vec3(relative_q.x, relative_q.y, relative_q.z);

	vec3 angular_v = angle * axis;
	return angular_v;
}

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint leaf_index = baseID + local_index;

		if(leaf_index >= leaf_size) break;
		Leaf leaf = foliage[leaf_index];
		
		if(leaf.inv_mass != 0.0f){
			vec3 up = rotate_vec3(leaf.q, vec3(0, 1, 0));
			float angle;
			vec3 axis;
			CalculateAlignUpDirectionRotation(leaf.q, vec3(0, 1, 0), angle, axis);
			leaf.torque += axis * angle * rotation_correction_strength;
			float l_a = length(leaf.acceleration);
			leaf.torque += vec3(EE_SIMPLEX_NOISE(leaf.x * disturbance_frequency.x) * 2.f - 1.f, EE_SIMPLEX_NOISE((leaf.x + vec3(10.f, 10.f, 10.f)) * disturbance_frequency.y) * 2.f - 1.f, EE_SIMPLEX_NOISE((leaf.x + vec3(20.f, 20.f, 20.f)) * disturbance_frequency.z) * 2.f - 1.f)
							* l_a * disturbance_strength;
			leaf.acceleration += up * l_a * air_resistance_strength;
		}
		foliage[leaf_index].acceleration = leaf.acceleration;
		foliage[leaf_index].torque = leaf.torque;
	}
}