#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint leaf_size;
	float snow_intensity;
	float snow_retain_ratio;
};

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint leaf_index = baseID + local_index;

		if(leaf_index >= leaf_size) break;

		Leaf leaf = foliage[leaf_index];
		int group_index = segments[leaf.segment_handle].group_index;
		
		if(group_index == 0){
			leaf.property1 += snow_intensity;
		}else if(snow_intensity < 0.f){
			leaf.property1 += snow_intensity;
		}

		leaf.property1 = max(0.0f, leaf.property1);
		leaf.extra_mass += leaf.property1 * (group_index == 0 ? 1.0f : snow_retain_ratio);
		foliage[leaf_index] = leaf;
	}
}