#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

struct RotationUpdate{
	vec4 new_rotation;
	uint index;
	uint padding0;
	uint padding1;
	uint padding2;
};

layout(std430, set = 1, binding = 0) readonly buffer POSITION_UPDATE_BLOCK {
  RotationUpdate rotation_updates[];
};

layout(push_constant) uniform PUSH_CONSTANTS {
	uint command_size;
};

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint global_index = baseID + local_index;

		if(global_index >= command_size) break;

		RotationUpdate rotation_update = rotation_updates[global_index];

		uint segment_index = rotation_update.index;

		vec4 new_rotation = rotation_update.new_rotation;

		Segment segment = segments[segment_index];
		segment.q = segment.last_q = new_rotation;
		segment.torque = vec3(0, 0, 0);
		segment.inv_mass = 0.0;

		segments[segment_index] = segment;
	}
}