#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

struct SegmentUpdate{
	vec4 new_rotation;
	vec3 new_particle0_position;
	uint segment_index;
	vec3 new_particle1_position;
	uint padding0;
};

layout(std430, set = 1, binding = 0) readonly buffer SEGMENT_UPDATE_BLOCK {
  SegmentUpdate segment_updates[];
};

layout(push_constant) uniform PUSH_CONSTANTS {
	uint command_size;
};

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint global_index = baseID + local_index;

		if(global_index >= command_size) break;

		SegmentUpdate segment_update = segment_updates[global_index];
		uint segment_index = segment_update.segment_index;
		Segment segment = segments[segment_index];
		segment.q = segment.last_q = segment_update.new_rotation;
		segment.torque = vec3(0, 0, 0);
		segment.inv_mass = 0.0;

		segment.particle0.x = segment.particle0.last_x = segment_update.new_particle0_position;
		segment.particle0.acceleration.xyz = vec3(0, 0, 0);
		segment.particle1.x = segment.particle1.last_x = segment_update.new_particle1_position;
		segment.particle1.acceleration.xyz = vec3(0, 0, 0);

		segments[segment_index] = segment;
	}
}