layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D sourceDepth;
layout(set = 0, binding = 1, r32f) uniform writeonly image2D targetMip;

layout(push_constant) uniform EE_DEPTH_PYRAMID_CONSTANTS {
  uvec2 sourceResolution;
  uvec2 targetResolution;
};

float FetchDepth(ivec2 texel) {
  ivec2 source_max = ivec2(sourceResolution) - ivec2(1);
  return texelFetch(sourceDepth, clamp(texel, ivec2(0), source_max), 0).r;
}

void main() {
  uvec2 pixel = gl_GlobalInvocationID.xy;
  if (pixel.x >= targetResolution.x || pixel.y >= targetResolution.y) {
    return;
  }

  ivec2 source_pixel = ivec2(pixel * 2);
  float depth = FetchDepth(source_pixel);
  if (sourceResolution.x != targetResolution.x || sourceResolution.y != targetResolution.y) {
    depth = min(depth, FetchDepth(source_pixel + ivec2(1, 0)));
    depth = min(depth, FetchDepth(source_pixel + ivec2(0, 1)));
    depth = min(depth, FetchDepth(source_pixel + ivec2(1, 1)));
  }
  imageStore(targetMip, ivec2(pixel), vec4(depth));
}
