#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_ray_query : require

#define EE_RAY_QUERY_SHADER
#include "RayTracingBasic.glsl"
#include "Random.glsl"
#include "GltfRasterMaterial.glsl"
#include "GltfRayTracingBsdf.glsl"
#include "CameraRayTracingPayload.glsl"

layout(set = 2, binding = 0, rgba32f) uniform image2D result_image;
layout(set = 2, binding = 1, r32f) uniform image2D ray_hit_distance_image;
layout(set = 2, binding = 2, rgba32f) uniform image2D radiance_history_image;
layout(set = 2, binding = 3, rgba32f) uniform image2D convergence_history_image;

layout(push_constant) uniform EE_CAMERA_CONSTANTS {
  uint EE_CAMERA_INDEX;
  uint EE_FRAME_ID;
  uint EE_TOTAL_SAMPLES;
  uint EE_FRAME_SAMPLE_SIZE;
  uint EE_SHADER_EXECUTION_REORDERING;
};

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

CameraRayTracingPayload hit_value;

#define EE_CAMERA_RAY_QUERY_TRAVERSAL
#include "CameraRayIntegrator.glsl"

void main() {
  const uvec2 pixel_coordinate = gl_GlobalInvocationID.xy;
  const uvec2 image_size = uvec2(imageSize(result_image));
  if (pixel_coordinate.x >= image_size.x || pixel_coordinate.y >= image_size.y) {
    return;
  }
  EE_CAMERA_RENDER_PIXEL(pixel_coordinate, image_size);
}
