#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint segment_size;
	float cell_size;
};

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint segment_handle = baseID + local_index;

		if(segment_handle >= segment_size) break;
		SegmentData segment_data = segment_data_list[segment_handle];
		
		Segment segment = segments[segment_handle];
		Particle particle0 = segment.particle0;
		Particle particle1 = segment.particle1;

		vec3 p0 = particle0.x;
		vec3 p1 = particle1.x;

		vec3 segment_center_position = (p0 + p1) * 0.5f;

		ivec3 coordinate;
		coordinate.x = int(segment_center_position.x / cell_size);
		coordinate.y = int(segment_center_position.y / cell_size);
		coordinate.z = int(segment_center_position.z / cell_size);
		int sum = 0;
		vec3 position_offset = vec3(0.0f, 0.0f, 0.0f);
		int group_index = segment.group_index;
		for(int x = -1; x <= 1; x++){
			for(int y = -1; y <= 1; y++){
				for(int z = -1; z <= 1; z++){
					ivec3 current_coordinate = coordinate + ivec3(x, y, z);
					uint cell_id = hash_cell_coordinate(current_coordinate);
					uint start_index = hashed_grid_cell_starts[cell_id].start_index;
					while(start_index != 0xFFFFFFFF && start_index < segment_size){
						uint neighbor_segment_handle = hashed_grid_elements[start_index].segment_handle;
						Segment neighbor_segment = segments[neighbor_segment_handle];
						if(neighbor_segment.group_index != group_index){
							Particle neighbor_particle0 = neighbor_segment.particle0;
							Particle neighbor_particle1 = neighbor_segment.particle1;

							vec3 neighbor_p0 = neighbor_particle0.x;
							vec3 neighbor_p1 = neighbor_particle1.x;

							vec3 neighbor_segment_center_position = (neighbor_p0 + neighbor_p1) * 0.5f;

							vec3 diff = segment_center_position - neighbor_segment_center_position;
							float diff_length = length(diff);
							vec3 direction = vec3(0, 0, 0);
							if(diff_length > 0.f){
								direction = normalize(diff);
							}

							sum++;
							position_offset += direction * max(0.0f, cell_size - diff_length);
						}
						start_index++;
					}
				}
			}
		}
		if(sum != 0){
			position_offset /= sum;
			segments[segment_handle].particle0.x += position_offset;
			segments[segment_handle].particle1.x += position_offset;
		}
	}
}