#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint segment_size;
	float cell_size;
};

void main(){
	int neighbor_segment_handles[BUNDLE_MAX_CONNECTION];
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint segment_handle = baseID + local_index;

		if(segment_handle >= segment_size) break;
		SegmentData segment_data = segment_data_list[segment_handle];
		
		[[unroll]] for (uint i = 0; i < BUNDLE_MAX_CONNECTION; i++) {
			neighbor_segment_handles[i] = -1;
			int pair_handle = segment_data.pair_handles[i];
			if (pair_handle < 0)
				continue;
			SegmentPair segment_pair = segment_pairs[pair_handle];
			if (segment_pair.valid == 0)
				continue;
			bool is_segment0 = segment_handle == segment_pair.segment0_handle;
			neighbor_segment_handles[i] = is_segment0 ? segment_pair.segment1_handle : segment_pair.segment0_handle;
		}

		Segment segment = segments[segment_handle];
		int particle0_handle = floatBitsToInt(segment.inertia_tensor_particle_0_handle.w);
		int particle1_handle = floatBitsToInt(segment.inv_inertia_tensor_particle_1_handle.w);
		Particle particle0 = particles[particle0_handle];
		Particle particle1 = particles[particle1_handle];

		vec3 p0 = particle0.x_node_handle.xyz;
		vec3 p1 = particle1.x_node_handle.xyz;
		vec3 segment_center_position = (p0 + p1) * 0.5f;

		ivec3 coordinate;
		coordinate.x = int(segment_center_position.x / cell_size);
		coordinate.y = int(segment_center_position.y / cell_size);
		coordinate.z = int(segment_center_position.z / cell_size);
		int sum = 0;
		vec3 position_offset = vec3(0.0f, 0.0f, 0.0f);

		for(int x = -1; x <= 1; x++){
			for(int y = -1; y <= 1; y++){
				for(int z = -1; z <= 1; z++){
					ivec3 current_coordinate = coordinate + ivec3(x, y, z);
					uint cell_id = hash_cell_coordinate(current_coordinate);
					uint start_index = hashed_grid_cell_starts[cell_id].start_index;
					while(start_index != 0xFFFFFFFF && start_index < segment_size){
						uint neighbor_segment_handle = hashed_grid_elements[start_index].segment_handle;
						bool found = false;
						for (uint i = 0; i < BUNDLE_MAX_CONNECTION; i++){
							if(neighbor_segment_handle == neighbor_segment_handles[i]){
								found = true;
								break;
							}
						}
						if(!found){
							Segment neighbor_segment = segments[neighbor_segment_handle];
							Particle neighbor_particle0 = particles[floatBitsToInt(neighbor_segment.inertia_tensor_particle_0_handle.w)];
							Particle neighbor_particle1 = particles[floatBitsToInt(neighbor_segment.inv_inertia_tensor_particle_1_handle.w)];

							vec3 neighbor_p0 = neighbor_particle0.x_node_handle.xyz;
							vec3 neighbor_p1 = neighbor_particle1.x_node_handle.xyz;
							vec3 neighbor_segment_center_position = (neighbor_p0 + neighbor_p1) * 0.5f;

							vec3 diff = segment_center_position - neighbor_segment_center_position;
							float diff_length = length(diff);
							vec3 direction = vec3(0, 0, 0);
							if(diff_length > 0.f){
								direction = normalize(diff);
							}

							sum++;
							position_offset += direction * max(0.0f, cell_size - diff_length);
						}
						start_index++;
					}
				}
			}
		}
		if(sum != 0){
			position_offset /= sum;
			particles[particle0_handle].x_node_handle.xyz += position_offset;
			particles[particle1_handle].x_node_handle.xyz += position_offset;
		}
	}
}