if (NOT DEFINED INPUT)
	message(FATAL_ERROR "INPUT is required.")
endif()

if (NOT EXISTS "${INPUT}")
	return()
endif()

file(READ "${INPUT}" exports)
string(REPLACE "\r\n" "\n" exports "${exports}")
string(REPLACE "\r" "\n" exports "${exports}")
string(REPLACE "\n" ";" export_lines "${exports}")

set(filtered_lines "EXPORTS")
foreach(line IN LISTS export_lines)
	string(STRIP "${line}" stripped)
	if (stripped STREQUAL "" OR stripped STREQUAL "EXPORTS")
		continue()
	endif()
	if (stripped MATCHES "^(__|_Avx2WmemEnabledWeakValue)([ \t]|$)")
		continue()
	endif()
	if (stripped MATCHES "(evo_engine|tinyply|ImGui|ImGuizmo|ImNodes|imnodes|ImVec|ImDraw|ImFont|ImColor|ImRect|ImPool|ImSpan|ImChunk|ImBit|GraphEditor|ImSequencer|ImCurveEdit|ImGradient|ImGuiFileDialog)")
		list(APPEND filtered_lines "${line}")
	endif()
endforeach()

list(JOIN filtered_lines "\n" filtered_exports)
file(WRITE "${INPUT}" "${filtered_exports}\n")
