function(evoengine_collect_boundary_targets directory output)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    evoengine_collect_boundary_targets("${child}" child_targets)
    list(APPEND targets ${child_targets})
  endforeach()
  set(${output} ${targets} PARENT_SCOPE)
endfunction()

function(evoengine_enforce_runtime_boundary)
  cmake_parse_arguments(BOUNDARY "" "ROOT;CHECKER" "TARGETS;EDITOR_ROOTS" ${ARGN})
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  evoengine_collect_boundary_targets("${BOUNDARY_ROOT}" targets)
  # Include imported targets and aliases referenced through generator expressions.
  set(pending ${targets})
  set(aliases "")
  while(pending)
    list(POP_FRONT pending target)
    foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
      get_target_property(links ${target} ${property})
      string(REGEX MATCHALL "[A-Za-z0-9_.+-]+(::[A-Za-z0-9_.+-]+)*" candidates "${links}")
      foreach(candidate IN LISTS candidates)
        if(TARGET "${candidate}")
          get_target_property(original ${candidate} ALIASED_TARGET)
          if(original)
            string(APPEND aliases "${candidate}=${original}\n")
            set(candidate ${original})
          endif()
          if(NOT candidate IN_LIST targets)
            list(APPEND targets ${candidate})
            list(APPEND pending ${candidate})
          endif()
        endif()
      endforeach()
    endforeach()
  endwhile()
  set(directory "${CMAKE_BINARY_DIR}/RuntimeBoundary/$<CONFIG>")
  set(index "@root\n${BOUNDARY_ROOT}\n@runtime\n$<JOIN:${BOUNDARY_TARGETS},\n>\n@editor_roots\n$<JOIN:${BOUNDARY_EDITOR_ROOTS},\n>\n@aliases\n${aliases}")
  file(GENERATE OUTPUT "${directory}/index.txt" CONTENT "${index}")
  foreach(target IN LISTS targets)
    get_target_property(type ${target} TYPE)
    if(type STREQUAL "UTILITY")
      continue()
    endif()
    get_target_property(source_dir ${target} SOURCE_DIR)
    set(content "@name\n${target}\n@source_dir\n${source_dir}\n")
    foreach(property INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES LINK_LIBRARIES
        INTERFACE_LINK_LIBRARIES SOURCES INTERFACE_SOURCES PRECOMPILE_HEADERS INTERFACE_PRECOMPILE_HEADERS)
      string(APPEND content "@${property}\n$<JOIN:$<TARGET_GENEX_EVAL:${target},$<TARGET_PROPERTY:${target},${property}>>,\n>\n")
    endforeach()
    string(REPLACE "::" "_" filename "${target}")
    file(GENERATE OUTPUT "${directory}/targets/${filename}.txt" CONTENT "${content}")
  endforeach()
  add_custom_target(EvoEngineRuntimeBoundary
    COMMAND "${Python3_EXECUTABLE}" "${BOUNDARY_CHECKER}" --graph "${directory}"
    VERBATIM)
  foreach(target IN LISTS BOUNDARY_TARGETS)
    add_dependencies(${target} EvoEngineRuntimeBoundary)
  endforeach()
endfunction()
