find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(EVOENGINE_BUILD_IDENTITY_DIR "${CMAKE_BINARY_DIR}/BuildIdentity/$<CONFIG>")
set(EVOENGINE_RUNTIME_BUILD_IDENTITY_DIR "${CMAKE_BINARY_DIR}/RuntimeBuildIdentity/$<CONFIG>")

function(evoengine_json_string output value)
	string(REPLACE "\\" "\\\\" value "${value}")
	string(REPLACE "\"" "\\\"" value "${value}")
	string(REPLACE "\n" "\\n" value "${value}")
	string(REPLACE "\r" "\\r" value "${value}")
	string(REPLACE "\t" "\\t" value "${value}")
	set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(evoengine_runtime_payload)
	if(NOT EVOENGINE_ENABLE_RUNTIME_PACKAGES)
		message(FATAL_ERROR "Runtime templates require EVOENGINE_ENABLE_RUNTIME_PACKAGES.")
	endif()
	set(files "")
	set(host "null")
	set(host_target "")
	if(TARGET EvoEngineRuntime)
		set(host_target EvoEngineRuntime)
		set(host "{\"executable\":\"$<TARGET_FILE_NAME:EvoEngineRuntime>\",\"pdb\":$<IF:$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>,\"$<TARGET_PDB_FILE_NAME:EvoEngineRuntime>\",null>}")
		list(APPEND files
			"{\"source\":\"$<TARGET_FILE:EvoEngineRuntime>\"}"
			"{\"source\":\"$<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:$<TARGET_PDB_FILE:EvoEngineRuntime>>\"}")
	endif()
	foreach(source IN LISTS EVOENGINE_RUNTIME_PAYLOAD_LIBRARIES)
		list(APPEND files "{\"source\":\"${source}\"}")
	endforeach()
	list(APPEND files "{\"source\":\"${EVOENGINE_RUNTIME_BUILD_IDENTITY_DIR}/evoengine-build.json\"}")
	foreach(target IN ITEMS EvoEngine_SDK glfw)
		list(APPEND files "{\"source\":\"$<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:$<TARGET_PDB_FILE:${target}>>\"}")
	endforeach()
	set(resources "{\"source\":\"${EVOENGINE_SDK_DIR}/Internals\",\"destination\":\".\"}")
	foreach(source IN LISTS EVOENGINE_RESOURCES)
		list(APPEND resources "{\"source\":\"${source}\",\"destination\":\".\"}")
	endforeach()
	set(packages "")
	foreach(target IN LISTS EvoEngine_RuntimePackages)
		get_target_property(name ${target} EVOENGINE_PACKAGE_NAME)
		get_target_property(dependencies ${target} EVOENGINE_PACKAGE_DEPENDENCIES)
		get_target_property(resource_dirs ${target} EVOENGINE_PACKAGE_RESOURCES)
		evoengine_json_array(dependencies ${dependencies})
		set(package_resources "")
		foreach(source IN LISTS resource_dirs)
			get_filename_component(folder "${source}" NAME)
			if(folder STREQUAL "Internals")
				file(GLOB children RELATIVE "${source}" "${source}/*")
				foreach(child IN LISTS children)
					list(APPEND package_resources "${child}")
				endforeach()
				set(folder ".")
			else()
				list(APPEND package_resources "${folder}")
			endif()
			list(APPEND resources "{\"source\":\"${source}\",\"destination\":\"${folder}\"}")
		endforeach()
		evoengine_json_array(package_resources ${package_resources})
		set(pdb "$<IF:$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>,\"Packages/$<TARGET_PDB_FILE_NAME:${target}>\",null>")
		list(APPEND packages "{\"name\":\"${name}\",\"dependencies\":${dependencies},\"library\":\"Packages/$<TARGET_FILE_NAME:${target}>\",\"manifest\":\"Packages/${name}.evepackage\",\"pdb\":${pdb},\"resources\":${package_resources}}")
		list(APPEND files
			"{\"source\":\"$<TARGET_FILE:${target}>\",\"destination\":\"Packages/$<TARGET_FILE_NAME:${target}>\"}"
			"{\"source\":\"$<TARGET_FILE_DIR:${target}>/${name}.evepackage\",\"destination\":\"Packages/${name}.evepackage\"}"
			"{\"source\":\"$<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:$<TARGET_PDB_FILE:${target}>>\",\"destination\":\"Packages/$<TARGET_PDB_FILE_NAME:${target}>\"}")
	endforeach()
	set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
	include(InstallRequiredSystemLibraries)
	foreach(source IN LISTS CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
		list(APPEND files "{\"source\":\"${source}\"}")
	endforeach()
	set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS "")
	set(CMAKE_INSTALL_DEBUG_LIBRARIES TRUE)
	set(CMAKE_INSTALL_DEBUG_LIBRARIES_ONLY TRUE)
	set(CMAKE_INSTALL_UCRT_LIBRARIES TRUE)
	include(InstallRequiredSystemLibraries)
	foreach(source IN LISTS CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
		list(APPEND files "{\"source\":\"$<$<CONFIG:Debug>:${source}>\"}")
	endforeach()
	list(JOIN files "," files)
	list(JOIN resources "," resources)
	list(JOIN packages "," packages)
	set(payload_dir "${CMAKE_BINARY_DIR}/RuntimePayload/$<CONFIG>")
	file(GENERATE OUTPUT "${payload_dir}/layout.json" CONTENT
"{\"schema_version\":1,\"identity_file\":\"${EVOENGINE_RUNTIME_BUILD_IDENTITY_DIR}/evoengine-build.json\",\"host\":${host},\"files\":[${files}],\"resource_directories\":[${resources}],\"packages\":[${packages}]}\n")
	add_custom_target(EvoEngineRuntimePayload
		COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/Scripts/write_build_identity.py" --spec "${EVOENGINE_BUILD_IDENTITY_DIR}/spec.json" --runtime-metadata "${EVOENGINE_RUNTIME_BUILD_IDENTITY_DIR}/evoengine-build.json" --verify
		COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/Scripts/prepare_runtime_template.py" --layout "${payload_dir}/layout.json" --output "${payload_dir}/template"
		DEPENDS EvoEngineRuntimeBuildIdentity EvoEngine_SDK ${EvoEngine_RuntimePackages} ${host_target}
		VERBATIM)
endfunction()

function(evoengine_json_array output)
	set(values "")
	foreach(value IN LISTS ARGN)
		evoengine_json_string(quoted "${value}")
		list(APPEND values "${quoted}")
	endforeach()
	list(JOIN values "," values)
	set(${output} "[${values}]" PARENT_SCOPE)
endfunction()

function(evoengine_finalize_native_build)
	set(options "")
	set(package_options "")
	get_cmake_property(cache_variables CACHE_VARIABLES)
	list(SORT cache_variables)
	foreach(key IN LISTS cache_variables)
		if(key MATCHES "^EVOENGINE_ENABLE_.*_PACKAGE$")
			evoengine_json_string(value "${${key}}")
			list(APPEND package_options "\"${key}\":${value}")
		elseif(key MATCHES "^CMAKE_(CXX_FLAGS|C_FLAGS|SHARED_LINKER_FLAGS|MSVC_RUNTIME_LIBRARY)" OR
			key MATCHES "^EVOENGINE_ENABLE_.*_SERVICE$" OR
			key MATCHES "^EVOENGINE_ENABLE_(RUNTIME_PACKAGES|GRAPHICS_VALIDATION)$")
			evoengine_json_string(value "${${key}}")
			list(APPEND options "\"${key}\":${value}")
		endif()
	endforeach()
	list(JOIN options "," options)
	list(JOIN package_options "," package_options)
	set(packages "")
	foreach(target IN LISTS EvoEngine_RuntimePackages)
		get_target_property(source_dir ${target} SOURCE_DIR)
		get_target_property(binary_dir ${target} BINARY_DIR)
		get_target_property(name ${target} EVOENGINE_PACKAGE_NAME)
		file(RELATIVE_PATH relative_source "${CMAKE_SOURCE_DIR}" "${source_dir}")
		get_target_property(dependencies ${target} EVOENGINE_PACKAGE_DEPENDENCIES)
        get_target_property(editor_dependencies ${target} EVOENGINE_EDITOR_DEPENDENCIES)
        if(NOT editor_dependencies)
            set(editor_dependencies "")
        endif()
        evoengine_json_array(editor_dependencies ${editor_dependencies})
		evoengine_json_array(dependencies ${dependencies})
		list(APPEND packages "{\"name\":\"${name}\",\"dependencies\":${dependencies},\"editor_dependencies\":${editor_dependencies},\"roots\":[\"${relative_source}\"],\"header\":\"${binary_dir}/BuildIdentity/$<CONFIG>/EvoEnginePackageBuildIdentity.hpp\"}")
	endforeach()
	list(JOIN packages "," packages)
	set(architecture "${CMAKE_SYSTEM_PROCESSOR}")
	if(CMAKE_GENERATOR_PLATFORM STREQUAL "x64" OR architecture MATCHES "^(AMD64|x86_64)$")
		set(architecture x64)
	endif()
	set(with_editor false)
	if(EVOENGINE_WITH_EDITOR)
		set(with_editor true)
	endif()
	set(identity_dir "${EVOENGINE_BUILD_IDENTITY_DIR}")
	file(GENERATE OUTPUT "${identity_dir}/spec.json" CONTENT
"{\"source_root\":\"${CMAKE_SOURCE_DIR}\",\"host_roots\":[\"EvoEngine_App/src/EvoEngineRuntime.cpp\",\"EvoEngine_App/resources/EvoEngineRuntime.rc\",\"EvoEngine_App/resources/EvoEngineRuntime.manifest\",\"EvoEngine_App/resources/EvoEngineLauncher.ico\"],\"sdk_roots\":[\"EvoEngine_SDK\",\"EvoEngine_Services\",\"cmake\",\"CMakeLists.txt\",\"EvoEngine_Packages/include\",\"EvoEngine_Packages/src\",\"EvoEngine_Packages/CMakeLists.txt\",\"Scripts/write_build_identity.py\"],\"packages\":[${packages}],\"compiler_id\":\"${CMAKE_CXX_COMPILER_ID}\",\"compiler_version\":\"${CMAKE_CXX_COMPILER_VERSION}\",\"configuration\":\"$<CONFIG>\",\"platform\":\"${CMAKE_SYSTEM_NAME}\",\"architecture\":\"${architecture}\",\"build_options\":{${options}},\"package_options\":{${package_options}},\"with_editor\":${with_editor},\"sdk_header\":\"${identity_dir}/EvoEngineBuildIdentity.hpp\",\"metadata_json\":\"${identity_dir}/evoengine-build.json\",\"metadata_cmake\":\"${identity_dir}/identity.cmake\"}\n")
	add_custom_target(EvoEngineBuildIdentity
		COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/Scripts/write_build_identity.py" --spec "${identity_dir}/spec.json"
		VERBATIM)
	add_custom_target(EvoEngineRuntimeBuildIdentity
		COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/Scripts/write_build_identity.py" --spec "${identity_dir}/spec.json" --runtime-metadata "${EVOENGINE_RUNTIME_BUILD_IDENTITY_DIR}/evoengine-build.json"
		DEPENDS EvoEngineBuildIdentity
		VERBATIM)
	add_dependencies(EvoEngine_SDK EvoEngineBuildIdentity)
	if(WIN32 AND architecture STREQUAL "x64" AND EVOENGINE_ENABLE_RUNTIME_PACKAGES)
		evoengine_runtime_payload()
	endif()
endfunction()
