#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrandsPhysics.glsl"

const uint WORKGROUP_SIZE = EXT_TASK_SUBGROUP_COUNT * EXT_TASK_SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((EXT_INVOCATIONS_PER_TASK + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * EXT_INVOCATIONS_PER_TASK;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint connection_size;
};


void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint connection_index = baseID + local_index;

		if(connection_index >= connection_size) break;

		Connection connection = connections[connection_index];
		Segment segment0 = segments[connection.segment0_handle];
		Segment segment1 = segments[connection.segment1_handle];
		vec3 bend_twist_strain = bend_twist_strain(segment0.q, segment1.q, connection.rest_darboux_vector);
		bool valid = connection.bend_twist_strain_valid.w != 0.0 
						&& bend_twist_strain.x < connection.max_bend_twist_strain.x
						&& bend_twist_strain.y < connection.max_bend_twist_strain.y
						&& bend_twist_strain.z < connection.max_bend_twist_strain.z
						
						&& segment0.stretch_shear_strain_original_inv_mass.x < segment0.max_stretch_shear_strain.x
						&& segment0.stretch_shear_strain_original_inv_mass.y < segment0.max_stretch_shear_strain.y
						&& segment0.stretch_shear_strain_original_inv_mass.z < segment0.max_stretch_shear_strain.z

						&& segment1.stretch_shear_strain_original_inv_mass.x < segment1.max_stretch_shear_strain.x
						&& segment1.stretch_shear_strain_original_inv_mass.y < segment1.max_stretch_shear_strain.y
						&& segment1.stretch_shear_strain_original_inv_mass.z < segment1.max_stretch_shear_strain.z;
		connections[connection_index].bend_twist_strain_valid = vec4(bend_twist_strain, valid ? 1.0 : 0.0);
	}
}