#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = EXT_TASK_SUBGROUP_COUNT * EXT_TASK_SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((EXT_INVOCATIONS_PER_TASK + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * EXT_INVOCATIONS_PER_TASK;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	uint particle_size;
	float time_step;
	float inv_time_step;
};

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint particle_index = baseID + local_index;

		if(particle_index >= particle_size) break;

		Particle particle = particles[particle_index];
		Segment segment = segments[floatBitsToInt(particle.old_x_segment_handle.w)];
		//Calculate velocity and apply acceleration.
		vec3 velocity = vec3(0, 0, 0);
		if(segment.inv_mass != 0.0){
			velocity = inv_time_step * (1.5 * particle.x_node_handle.xyz - 2.0 * particle.old_x_segment_handle.xyz + 0.5 * particle.last_x_strand_handle.xyz);
			velocity += particle.acceleration_connectivity_strain.xyz * time_step;
		}
		velocity *= 1.0 - particle.x0_damping.w;
		//Shift position values
		particle.last_x_strand_handle.xyz = particle.old_x_segment_handle.xyz;
		particle.old_x_segment_handle.xyz = particle.x_node_handle.xyz;
		//Apply velocity
		particle.x_node_handle.xyz += time_step * velocity;
		particles[particle_index] = particle;
	}
}