#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_ARB_shading_language_include : enable
#extension GL_EXT_control_flow_attributes : require

#define DYNAMIC_STRANDS_SET 0
#include "DynamicStrands.glsl"
#include "Math.glsl"

const uint WORKGROUP_SIZE = COMPUTE_SUBGROUP_COUNT * SUBGROUP_SIZE;

const uint ITERATIONS_PER_TASK = ((COMPUTE_WORK_GROUP_INVOCATIONS + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE);

uint baseID = gl_WorkGroupID.x * COMPUTE_WORK_GROUP_INVOCATIONS;
uint laneID = gl_LocalInvocationID.x;

layout(local_size_x = WORKGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define BARRIER() \
memoryBarrierShared(); \
barrier();

layout(push_constant) uniform PUSH_CONSTANTS {
	vec4 obb_rotation;
	vec4 obb_center;
	vec4 obb_scale;
	float softness;
	uint segment_size;
	float friction;
	float rotational_friction;
};

void process_point(inout vec3 p0, inout vec3 p1, inout vec4 q, in vec3 v0, in vec3 v1, inout vec3 torque, inout vec3 acceleration0, inout vec3 acceleration1, inout int reach_ground){
	vec3 projected_p0 = p0 - obb_center.xyz;
	projected_p0 = rotate_vec3(conjugate(obb_rotation), projected_p0);
	vec3 projected_v0 = rotate_vec3(conjugate(obb_rotation), v0);

	float abs_x = abs(projected_p0.x);
	float abs_y = abs(projected_p0.y);
	float abs_z = abs(projected_p0.z);
	bool update_torque = false;
	if(abs_x < obb_scale.x && abs_y < obb_scale.y && abs_z < obb_scale.z){
		float factor_x = obb_scale.x - abs_x;
		float factor_y = obb_scale.y - abs_y;
		float factor_z = obb_scale.z - abs_z;

		if(factor_x <= factor_y && factor_x <= factor_z){
			if(projected_p0.x < 0.f){
				projected_p0.x -= softness * (obb_scale.x - abs_x);
			}else{
				projected_p0.x += softness * (obb_scale.x - abs_x);
			}
			acceleration0 -= length(vec3(0.f, projected_v0.y, projected_v0.z)) > 1e-9f ? friction * normalize(rotate_vec3(obb_rotation, vec3(0.f, projected_v0.y, projected_v0.z))) : vec3(0.f);
		}else if(factor_y <= factor_z){
			if(projected_p0.y < 0.f){
				projected_p0.y -= softness * (obb_scale.y - abs_y);
			}else{
				projected_p0.y += softness * (obb_scale.y - abs_y);
			}
			acceleration0 -= length(vec3(projected_v0.x, 0.f, projected_v0.z)) > 1e-9f ? friction * normalize(rotate_vec3(obb_rotation, vec3(projected_v0.x, 0.f, projected_v0.z))) : vec3(0.f);
		}else{
			if(projected_p0.z < 0.f){
				projected_p0.z -= softness * (obb_scale.z - abs_z);
			}else{
				projected_p0.z += softness * (obb_scale.z - abs_z);
			}
			acceleration0 -= length(vec3(projected_v0.x, projected_v0.y, 0.f)) > 1e-9f ? friction * normalize(rotate_vec3(obb_rotation, vec3(projected_v0.x, projected_v0.y, 0.f))) : vec3(0.f);
		}
		p0 = rotate_vec3(obb_rotation, projected_p0) + obb_center.xyz;
		update_torque = true;
                reach_ground = 1;
	}


	vec3 projected_p1 = p1 - obb_center.xyz;
	projected_p1 = rotate_vec3(conjugate(obb_rotation), projected_p1);
	vec3 projected_v1 = rotate_vec3(conjugate(obb_rotation), v1);

	abs_x = abs(projected_p1.x);
	abs_y = abs(projected_p1.y);
	abs_z = abs(projected_p1.z);

	if(abs_x < obb_scale.x && abs_y < obb_scale.y && abs_z < obb_scale.z) {
		float factor_x = obb_scale.x - abs_x;
		float factor_y = obb_scale.y - abs_y;
		float factor_z = obb_scale.z - abs_z;

		if(factor_x <= factor_y && factor_x <= factor_z){
			if(projected_p1.x < 0.f){
				projected_p1.x -= softness * (obb_scale.x - abs_x);
			}else{
				projected_p1.x += softness * (obb_scale.x - abs_x);
			}
			acceleration1 -= length(vec3(0.f, projected_v1.y, projected_v1.z)) > 1e-9f ? friction * normalize(rotate_vec3(obb_rotation, vec3(0.f, projected_v1.y, projected_v1.z))) : vec3(0.f);
		}else if(factor_y <= factor_z){
			if(projected_p1.y < 0.f){
				projected_p1.y -= softness * (obb_scale.y - abs_y);
			}else{
				projected_p1.y += softness * (obb_scale.y - abs_y);
			}
			acceleration1 -= length(vec3(projected_v1.x, 0.f, projected_v1.z)) > 1e-9f ? friction * normalize(rotate_vec3(obb_rotation, vec3(projected_v1.x, 0.f, projected_v1.z))) : vec3(0.f);
		}else{
			if(projected_p1.z < 0.f){
				projected_p1.z -= softness * (obb_scale.z - abs_z);
			}else{
				projected_p1.z += softness * (obb_scale.z - abs_z);
			}
			acceleration1 -= length(vec3(projected_v1.x, projected_v1.y, 0.f)) > 1e-9f ? friction * normalize(rotate_vec3(obb_rotation, vec3(projected_v1.x, projected_v1.y, 0.f))) : vec3(0.f);
		}
		p1 = rotate_vec3(obb_rotation, projected_p1) + obb_center.xyz;
		update_torque = true;
                reach_ground = 1;
	}
	/*
	if(update_torque){
		vec3 front = normalize(p0 - p1);
		float angle;
		vec3 axis;
		CalculateAlignFrontDirectionRotation(q, front, angle, axis);
		torque = axis * angle;
	}*/
}

void main(){
	[[unroll]]
	for (uint i = 0; i < ITERATIONS_PER_TASK; i++)
	{
		uint local_index  = laneID + i * WORKGROUP_SIZE;
		uint segment_index = baseID + local_index;

		if(segment_index >= segment_size) break;

		Segment segment = segments[segment_index];
		process_point(segment.particle0.x, segment.particle1.x, segment.q, segment.particle0.v, segment.particle1.v, segment.torque, segment.particle0.acceleration, segment.particle1.acceleration, segment.reach_ground);
		segments[segment_index].torque = segment.torque;
		segments[segment_index].particle0.x = segment.particle0.x;
		segments[segment_index].particle1.x = segment.particle1.x;
		segments[segment_index].particle0.acceleration = segment.particle0.acceleration;
		segments[segment_index].particle1.acceleration = segment.particle1.acceleration;
                segments[segment_index].reach_ground = segment.reach_ground;
                if (segment.reach_ground == 1) {
                  segments[segment_index].quasi_stable = 1;
                }
	}
}