set(DIGITAL_AGRICULTURE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})

set(DIGITAL_AGRICULTURE_INCLUDES
	${DIGITAL_AGRICULTURE_DIRECTORY}/include
	${DIGITAL_AGRICULTURE_DIRECTORY}/include/CropModel
	${DIGITAL_AGRICULTURE_DIRECTORY}/include/SorghumModel
	)

file(GLOB_RECURSE DIGITAL_AGRICULTURE_HEADERS ${DIGITAL_AGRICULTURE_DIRECTORY}/include/*.hpp)
file(GLOB_RECURSE DIGITAL_AGRICULTURE_SOURCES ${DIGITAL_AGRICULTURE_DIRECTORY}/src/*.cpp)

add_library(DigitalAgriculturePackage
	SHARED
	${DIGITAL_AGRICULTURE_HEADERS}
	${DIGITAL_AGRICULTURE_SOURCES}
	)
target_compile_definitions(DigitalAgriculturePackage
	PUBLIC
	DIGITAL_AGRICULTURE_PACKAGE
	PRIVATE
	${EVOENGINE_SDK_DEFS}
	${EVOENGINE_SERVICES_DEFS}
	)
target_include_directories(DigitalAgriculturePackage
	PUBLIC
	${EVOENGINE_SDK_INCLUDES}
	${DIGITAL_AGRICULTURE_INCLUDES}
	PRIVATE
	${EVOENGINE_SERVICES_INCLUDES}
	)
target_link_libraries(DigitalAgriculturePackage
	PUBLIC
	EcoSysLabPackage
	GprPackage
	PRIVATE
	EvoEngine_SDK
	${EvoEngine_Services}
	)

set(DIGITAL_AGRICULTURE_PCH ${DIGITAL_AGRICULTURE_DIRECTORY}/include/DigitalAgriculture_PCH.hpp)
evoengine_configure_runtime_package(DigitalAgriculturePackage
	EXTRA_PCH ${DIGITAL_AGRICULTURE_PCH}
	RESOURCES ${CMAKE_CURRENT_SOURCE_DIR}/Internals
	)
